### ISSUE TITLE
"Show" button from the reset password page should only react on second press if the textarea is not in focus [bz1229749]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#100]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1229749

Reproduced on Mac OS X 10.11 using:
*Firefox 42
*Firefox 43 beta 8
*latest 44.0a2 Aurora
*latest 45.0a1 Nightly

STR:
_pre-requisite:
*_the user has a FxAccount.
1. Open Firefox using a clean profile.
2. Click on one of the available Sync buttons (e.g. about:home, about:preferences#sync, menu panel, Tools).
3. Select “Sign in” and click the "Forget password?" link.
4. Enter your email address and wait for the 'Reset password........' email. Click on the link received in the email.
5. Focus the first text field (New Password) and enter some data.
6. Focus the second field and enter some data.
7. Click outside the text fields, anywhere else on the page.
8. Select “Show” for the New Password field.

Expected Result:
The text entered in the “New Password” field is revealed.

Actual Result:
On first click, the text field is focused/selected and only on the second click the "Show" button reacts (you have to click twice in order to reveal the text).

Notes:
This issue also reproduces on Windows 7 64-bit, Windows 7 32-bit and Ubuntu 14.04 32-bit.
This is not a recent regression.

**Comment by vladikoff** [comment]
Fixed, ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1229749#c4
