### ISSUE TITLE
Reduce FxA email verification polling [bz1235607]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#103]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1235607

Currently, FxAccounts.jsm polls the auth server to check whether the user has verified their email address.

The auth server is to be updated with support for push notifications in [1] so that the polling can be eliminated. This issue exists to cover the associated changes to the browser code.

[1] https://github.com/mozilla/fxa-auth-server/issues/1141

**Comment by vladikoff** [comment]
@philbooth commented https://bugzilla.mozilla.org/show_bug.cgi?id=1235607#c1

**Comment by vladikoff** [comment]
from mtg: need to check when we want this done and who got bandwidth

**Comment by rfk** [comment]
We have enough on our plates this cycle, with @philbooth out I think we should pause this until we ship the AMO stuff (which will hopefully be this cycle).

**Comment by vladikoff** [comment]
Closing this, left to do: https://github.com/mozilla/fxa-bugzilla-mirror/issues/132
