### ISSUE TITLE
head.js original source is a 404 page [bz1236388]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#104]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1236388

User Agent: Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0
Build ID: Gecko/20100101

Steps to reproduce:

If I fire up the developer tools while logging in to FF Sync via about:accounts, the source for head.js is by default a 404 HTML page.

Actual results:

The browser loaded <https://accounts.firefox.com/scripts/f96ef6f6.head.js>. Because the developer tools option "Show Original Sources" was on (the default), it then loaded <https://accounts.firefox.com/scripts/head.js.map>, which in turn pointed it to the original source "../../.tmp/concat/scripts/head.js", which evaluates to <https://accounts.firefox.com/.tmp/concat/scripts/head.js>, which returns an HTML 404 page.

Expected results:

The source that was minified into https://accounts.firefox.com/scripts/f96ef6f6.head.js should be available at <https://accounts.firefox.com/scripts/head.js> (similarly to main.js).

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-content-server/issues/3355
