### ISSUE TITLE
Device management/dashboard [bz1238698]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#116]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1238698

I'd like to see all devices on sync, remove them from sync, and see the last time they synced.

**Comment by shane-tomlinson** [comment]
@ryanfeeley has ideas on providing UX within Firefox that links to the FxA devices view instead of implementing a new device view. Closing as "we already have the start of this!"
