### ISSUE TITLE
Unable to upload picture to Firefox Accounts from firstrun [bz1238932]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#117]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1238932

Created attachment 8706901
Gif showing the issue

Affected builds:

Affected OS's:

STR:
1. Start Firefox
2. Visit https://www.mozilla.org/en-US/firefox/44.0/firstrun/ or 43.0 instead of 44.0 
3. Sign in with a new account
4. Revisit url from step 2
5. Click 'Add' button from Account picture
6. Click Upload and select an image from drive

Expected: The selected image is uploaded to FxA

Actual: Nothing happens after selecting the image.

Notes:
- Not sure if this is a recent regression, it also reproduces in 43.0, will get back on this asap.
- Doing the same thing from https://accounts.firefox.com/settings works as expected

**Comment by shane-tomlinson** [comment]
Closing as a dup of https://github.com/mozilla/fxa-content-server/issues/3388
