### ISSUE TITLE
Support to saving data in change password message [bz1236641]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#118]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1236641

Motivation: https://input.mozilla.org/en-US/dashboard/response/5763308

Current forget password wording
" Resetting your password will erase your browsing data from our servers. Any data on your devices will remain untouched. Begin the reset process by entering your email below. "

Adding a wording here that explains that the data that is on the local computer will be what is synced if you reset your password. Previous synced data will not be accessible. To avoid data loss, make sure you have a local back up...

Or something like this to warn the common mistake if they find themselves in the situation mentioned in the input link above.

**Comment by shane-tomlinson** [comment]
cc @ryanfeeley

**Comment by ryanfeeley** [comment]
@rfk @shane-tomlinson  Working on a PR will all proposed changes.

**Comment by ryanfeeley** [comment]
I think this issue pre-dates our copy changes, but I would like to propose this improvement:
![reset-account](https://cloud.githubusercontent.com/assets/68213/21277400/27220764-c3a4-11e6-9c9a-77ad21f92a85.png)

**Comment by rfk** [comment]
@ryanfeeley I like it;  See also https://bugzilla.mozilla.org/show_bug.cgi?id=1320213 which as an additionl security-related tweak to this flow.

**Comment by rfk** [comment]
The bugzilla bug this references is resolved/fixed, but I'm assigning myself to capture @ryanfeeley's changes above, and the one in https://bugzilla.mozilla.org/show_bug.cgi?id=1320213, as a separate piece of work.

**Comment by rfk** [comment]
Re-filed with latest combined suggestions at https://github.com/mozilla/fxa-content-server/issues/4538
