### ISSUE TITLE
Improve user information in the reset password e-mail [bz1243004]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#121]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1243004

In the very first step (https://accounts.firefox.com/reset_password) the user is informed about the password reset consequences, but that's also the last time. Thus a lot of cases are in the support forum, about data deleted when password has been reset.

I suggest to add this information also to the confirmation e-mail, together with a link to cancel the password reset process, just for the users to make sure, nothing has been deleted yet.

It should be there also for the case, when someone just filed my e-mail address in the form and I accidentally click on the big blue button in the e-mail, without being informed about the possible impact.

**Comment by shane-tomlinson** [comment]
Hey @ryanfeeley, are you already working on this?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Yes, already a PR. https://github.com/mozilla/fxa/blob/rfeeley/reset-password/features/FxA-72-reset-password/README.md 
Should I close this?

**Comment by rfk** [comment]
Designs ready, closing this in favour of https://github.com/mozilla/fxa-content-server/issues/3467

**Comment by MikkCZ** [comment]
Well, none of the proposed UX https://github.com/mozilla/fxa/blob/rfeeley/reset-password/features/FxA-72-reset-password/README.md is about the information contained in the e-mails. Or is it?

**Comment by rfk** [comment]
The one with "Alternatively {{ link }}" is the content of the actual email (although it hasn't changed very much in this design)

**Comment by rfk** [comment]
The most important change here is the warning on the page that actually performs the reset, which is where you'll wind up if yo follow the link in the email.  In this old version this page didn't say anything about the consequences of a password reset.
