### ISSUE TITLE
400 errors during device registration [bz1243594]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#123]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1243594

From bug 1195569 in attachment 8712941 we can see the following entries:

> 1453935569159	FirefoxAccounts	ERROR	error POSTing /account/device: {"code":400,"errno":999,"error":"Bad Request","message":"Invalid request payload JSON format","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
> 1453935569160	FirefoxAccounts	ERROR	device registration failed: {"code":400,"errno":999,"error":"Bad Request","message":"Invalid request payload JSON 

We should try and work out what this means.

**Comment by vladikoff** [comment]
@rfk this is for the Desktop client, not sure if we can lose this here?

**Comment by rfk** [comment]
The desktop client is still our responsibility; we can lose this mirror issue if it's not providing any value, but musn't we let the bug itself fall off our radar, so I kinda like having it represented in our waffleboard.

**Comment by rfk** [comment]
Looks like @mhammond has a patch for this in the bugzilla bug, closing it out here
