### ISSUE TITLE
about:accounts shows a 500 error attempting to signin (even though Firefox should be taking you to the reauth page rather than the signin page) [bz1250451]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#131]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1250451

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0
Build ID: 20160209234642

Steps to reproduce:

1. Reset sync on computer 1
2. Sync fails on computer 2 (expected)
3a. Attempt to set the new password on computer 2.
3b. Use help page info to clear sync account from computer 2, attempt to log in to account with computer 2.
3c. Attempt to create new account with computer 2.

Actual results:

3a, 3b, 3c all produce HTTP 500 errors on multiple attempts spread over more than 24 hours.

Expected results:

3a/3b should have let me log in to my Sync account.
3c should have let me create a new Sync account.

**Comment by shane-tomlinson** [comment]
ref #3040, #3057, #3283

**Comment by rfk** [comment]
The most relevant of the screenshots in the bug was this one: https://bugzilla.mozilla.org/attachment.cgi?id=8723476

**Comment by shane-tomlinson** [comment]
Ahha, this is a dup of mozilla/fxa-content-server#3466, copying STRs, info and closing.
