### ISSUE TITLE
Add quality metrics for FxA Verification via Push [bz1249029]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#132]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1249029

We need to be able to measure if FxA Verification via Push works properly. 

This issue is related to: https://bugzilla.mozilla.org/show_bug.cgi?id=1235607
It does not block the issue above.

**Comment by vladikoff** [comment]
In review at https://reviewboard.mozilla.org/r/40301

**Comment by vladikoff** [comment]
Landed in https://bugzilla.mozilla.org/show_bug.cgi?id=1249029#c12
