### ISSUE TITLE
ff fails to remember login for accounts.firefox.com [bz1258135]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#133]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1258135

User Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Build ID: 20160304160129

Steps to reproduce:

went to https://accounts.firefox.com/signin expected auto remember dialogue, entered details manually to login manager, and auto-fill fails

it's a pita to have to manually copy pwords from one instance of ff to another - my pwords are far to complicated to remember - I rely on ff's pword/ login manager for that

Actual results:

remember login; auto-fill fails at https://accounts.firefox.com/signin

Expected results:

login remembered; auto-fill works at https://accounts.firefox.com/signin

**Comment by vladikoff** [comment]
need to discuss this more ....

**Comment by vladikoff** [comment]
Closed in https://bugzilla.mozilla.org/show_bug.cgi?id=1258135
