### ISSUE TITLE
Sync Error 500 that I can't find any exact info about. [bz1261662]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#136]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1261662

Created attachment 8737586
FireShot Capture 12 - Firefox Sync - about_accounts_action=reauth&entrypoint=syncbutton.png

User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:44.0) Gecko/20100101 Firefox/44.0.3 Waterfox/44.0.3
Build ID: 20160218160818

Steps to reproduce:

I first noticed on the sync icon after 1:00am CST;hovering it says "Reconnect stuartp99@vfemail.net".So I clicked on Options then Privacy and checked Accept cookies from sites and accept third-party cookies.Then went to sign in on Sync and found Error 500 saying "Oh dear,something went wrong there.We've been notified and will get working on a fix."

Actual results:

I tried looking under Firefox help to find an answer to Error 500 under Firefox Sync and found nothing that matches my OS Windows 8.1.

Expected results:

I should have immediately been able to sign in without this strange 500 Error.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1261662#c24
