### ISSUE TITLE
Create Firefox Desktop retention graph for email subscribers vs. non-email subscribers

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#149]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1261372

**Comment by shane-tomlinson** [comment]
@philbooth - are you working on this already?

**Comment by rfk** [comment]
I have the data for the first version of this, next action is with me but looping in @philbooth to collaborate is a good idea :-)

**Comment by rfk** [comment]
Closing in favour of the fxa-bugzilla-mirror-managed issue at #157
