### ISSUE TITLE
Automatically re-send verification email after logging in, if account was created long ago [bz976713]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#15]
From https://bugzilla.mozilla.org/show_bug.cgi?id=976713

Create an account. Don't verify it.

Come back a week later and sign in.

You'll get a screen on your phone: "A verification link has been sent to...".

That implies that it was *just* sent. In fact, it was sent a week ago. (Or more.)

You have to click "Resend email" to get unblocked.

Proposal: if a sign-in occurs, on an unverified account, where the verification email was sent more than N hours ago, send another verification email.

**Comment by vladikoff** [comment]
@ryanfeeley @rfk do we still want to do this? (or does verification reminders take care of this?)

**Comment by rfk** [comment]
@vladikoff if we did add this functionality, would it be straightforwardto "reset" the verification reminder countdown so that we don't send a verification link and a reminder in short succession?

**Comment by rfk** [comment]
(FWIW my take is that may still worth doing, because the experience as described can indeed be pretty confusing, and the verification reminders wont help you in the moment when you're trying to log in)
