### ISSUE TITLE
Confirm New Password Field Needed in Password Form [bz1266721]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#151]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1266721

Go to Menu and click on your account name if signed in your Firefox account or sign in and then click on the name.
Click on "Manage account"
On the "Password" field click "Change"

Now, here we see only two fields asking for the old one and the new password. Bur should have a Confirm New password. I myself entered a password and a moment later while signing in another device got my password wrong and had to restore using forgot password. So, for ensuring what I entered is what I wanted to enter as password, we should have a Confirm New Password, I think.

**Comment by vladikoff** [comment]
Moving to triage because seems like discussion got stuck a bit

**Comment by vladikoff** [comment]
cc @ryanfeeley

**Comment by vladikoff** [comment]
@ryanfeeley to triage this

**Comment by ryanfeeley** [comment]
@rfk We didn't have a "Repeat new password" field because we have "show password" which is probably even a better way to see what the password is. If we can't count on the show password field, I'm game for adding a "Repeat new password" field, but will have to include wording for some new error states. Assign to me if you think we will be relying less on show.

**Comment by vladikoff** [comment]
@ryanfeeley might wanna proxy the response to https://bugzilla.mozilla.org/show_bug.cgi?id=1266721

**Comment by vladikoff** [comment]
@rfk to prioritize

**Comment by rfk** [comment]
> If we can't count on the show password field [...]

Looks like we're going to keep the "Show Password" field, so per my comment at [1]  let's backlog this for Q3.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1266721#c8

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1266721#a54138067_481559
