### ISSUE TITLE
"X days ago" and similar strings lack placeables [bz1272968]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#154]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1272968

Not sure if this is the right component for this bug, so please move if necessary.

While reviewing translation suggestions for Firefox Accounts, I've found a bunch of "X foos ago" strings, which lack placeables, thus aren't fully localizeable.

The strings are defined here (thanks Axel for finding them!):
https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/settings/devices.js#L25

Please convert them to ones with placeables if possible. Thanks!

**Comment by vladikoff** [comment]
![devices-disconnect-and-refresh-only](https://cloud.githubusercontent.com/assets/68213/16558723/847f3ed4-41b5-11e6-929b-c1c3c9218712.png)

#### Some more context here: https://github.com/mozilla/fxa-content-server/issues/3907

**Comment by shane-tomlinson** [comment]
@vladikoff - I'm having a look at [jquery.timeago's configuration](https://github.com/rmm5t/jquery-timeago/blob/master/jquery.timeago.js#L55). I realize it's not an l10n best practice to ask for translations in an odd format [(non-ngettext)](http://linuxreviews.org/man/ngettext/index.html.en) because ngettext allows for "0", "1" and "more than 1", but it seems like even passing the list of available options allowed by jquery.timeago would be a huge improvement.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - can we get your input over here? I'd love to get these strings in a better place, and it looks [like you want to too](mozilla/fxa-content-server#3973).

**Comment by rfk** [comment]
I recall discussing the use of momentjs for this in the past, but don't recall any details of why we decided against it, @shane-tomlinson or @vladikoff do you recall the details there?  We're about to start using it in fxa-auth-mailer [1], albeit not for relative times.

[1] https://github.com/mozilla/fxa-auth-mailer/pull/180/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R28

**Comment by shane-tomlinson** [comment]
> I recall discussing the use of momentjs for this in the past

Because it's big. No more client side libraries unless absolutely necessary! I don't believe moment will give us anything we don't already have for this simple use case.

**Comment by vladikoff** [comment]
from irc:


> [09:23:44]  <vladikoff>	stomlinson, here's an idea, we put moment.js on the auth server and make it return "X centuries ago" when we request it with certain locales
[09:24:03]  <vladikoff>	stomlinson, and we put it on the oauth server to do the same for the apps


Thoughts @rfk @shane-tomlinson ?

**Comment by rfk** [comment]
So like, return a "humanReadableTimestamp" field in the JSON response  on `/account/devices`, and just blit it directly into the page?  Or a more elaborate/general-purpose hosted l10n API?  Either way, seems like it might be the simplest path forward on this issue, I'm open to the idea at a high level.
