### ISSUE TITLE
Set up a persistent ELB for Firefox Accounts [bz1277539]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#159]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1277539

From :jbuck in https://github.com/mozilla/fxa/issues/132:

> For each deploy we create a new ELB. CDN configuration changes take about 15
> minutes to process, so we'd be looking at a 30 minute rollback period. We 
> could add another Route53 entry and have the CDN always point at that and 
> on promotion change that to point at the correct ELB... but I'd prefer have 
> a single persistent ELB and not have to change CDN or DNS config at all.

**Comment by shane-tomlinson** [comment]
Closing as WONTFIX. We don't need this for a CDN.
