### ISSUE TITLE
Deploy lastest.dev.lcip.org static resources to a CDN [bz1277541]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#160]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1277541

To thoroughly test CDN deployments of FxA code, we should set up latest.dev.lcip.org to serve static resources from a CDN.

**Comment by rfk** [comment]
@shane-tomlinson I ran the fxa-bugzilla-mirror script and it sucked a bunch of CDN-related bugzilla bugs into our waffleboard.  Is it useful to have them represented here, or should we [fxa-waffle-ignore] them back into bugzilla?

**Comment by vladikoff** [comment]
@jrgm this might need a full rebuild of `latest` with CDN stuff on

**Comment by shane-tomlinson** [comment]
Latest is now on a CDN, closing. Thanks @jrgm and @jbuck!
