### ISSUE TITLE
Deploy https://accounts.stage.mozaws.net/ static resources to a CDN [bz1277542]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#161]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1277542

To thoroughly test CDN deployments of FxA code, we should set up latest.dev.lcip.org to serve static resources from a CDN.

**Comment by shane-tomlinson** [comment]
Stage is now deployed to a CDN, closing.

**Comment by vladikoff** [comment]
yay!
