### ISSUE TITLE
Deploy https://accounts.firefox.com static resources to a CDN [bz1277543]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#162]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1277543

The final step in deploying Firefox Accounts static resources to a CDN.

**Comment by shane-tomlinson** [comment]
prod now uses a CDN, closing. This is epic, thanks @jbuck for working through everything with me and to @jrgm for pushing it out the door!
