### ISSUE TITLE
Can't login to Marketplace on FxOS 1.3 [bz1279540]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#163]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1279540

Trying to login to Marketplace (either via consumer pages or devhub) results in a 500 error.  This is only occurring on FirefoxOS 1.3 - works fine on 2.0, 2.5 and desktop Firefox.  

The actual error appears to be on the FxA domain rather than Marketplace so the offending code may not reside in zamboni/fireplace.

**Comment by vladikoff** [comment]
@shane-tomlinson I checked it out and it seems like a CSP Error:

```
Content Security Policy: The page's settings blocked the loading of a resource at https://api.accounts.firefox.com/v1/account/login ("default-src https://accounts.firefox.com:443").(unknown)
```

![](http://v14d.com/i/578d36752fa26.jpg)

![image](https://cloud.githubusercontent.com/assets/128755/16928578/7452001c-4d01-11e6-9505-fdf24a4df91d.png)

**Comment by shane-tomlinson** [comment]
Does FxOS not understand `connect-src`? The CSP rules are:

> "connect-src 'self' https://api.accounts.firefox.com https://oauth.accounts.firefox.com https://profile.accounts.firefox.com https://accounts.firefox.com/basket; default-src 'self'; font-src 'self'; img-src 'self' data: https://secure.gravatar.com https://firefoxusercontent.com; media-src blob:; report-uri /_/csp-violation; script-src 'self' 'unsafe-eval'; style-src 'self' 'sha256-9n6ek6ecEYlqel7uDyKLy6fdGNo3vw/uScXSq9ooQlk='"
```

Maybe we have to be gross and UA sniff and alter the CSP rules appropriately for FxOS 1.3. I'll ask some of the local former-FxOS devs if they know about FxOS's CSP handling.

**Comment by shane-tomlinson** [comment]
OK, some good info from [MDN](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#connect-src).

> Note: Prior to Firefox 23, xhr-src was used in place of the connect-src directive and only restricted the use of XMLHttpRequest.

I believe FxOS 1.3 is based on Gecko 18, so this makes sense.
