### ISSUE TITLE
Renew SSL certificate for firefoxusercontent.com & mozillausercontent.com [bz1280038]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#164]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1280038

These certificates expire on September 8 2016, we should renew & deploy the new certificates.

mozillausercontent.com is in stage, and firefoxusercontent.com is in prod. I don't see any cloudformation scripts, so I think we'll just need to add the cert to IAM and update each CDN directly.

ckolos: Could/should we use Amazon Certificate Manager for this?

**Comment by vladikoff** [comment]
Blocked in bugzilla
