### ISSUE TITLE
[monitoring-story] dashboard for fraud and abuse stats [bz977329]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#17]
From https://bugzilla.mozilla.org/show_bug.cgi?id=977329

As a SRE/QA Manager, I want to see accounts and IPs that are hitting max failed password attempts.
Acceptance criteria:
- SRE has a dashboard to view potential fraud and abuse accounts and able to disable them.
- An email alert is sent when a large number of accounts are failing password attempts exceed a set threshold.
Timeframe: Fx29 Deploy

**Comment by vladikoff** [comment]
This might need a retriage ...
