### ISSUE TITLE
"Firefox Cloud Services Privacy Notice" makes no mention of encryption [bz1285844]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#170]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1285844

Reported via sumo at https://input.mozilla.org/en-US/dashboard/response/5951410

https://www.mozilla.org/en-US/privacy/firefox-cloud/ mentions under "Things you should know" that "If you use Sync, we receive a variety of information to synchronize your tabs, awesome bar, passwords, bookmarks, browser preferences and other data across devices."

A casual reader may conclude that the Sync server receives your passwords and bookmarks in a readable form, whereas they are encrypted and not readable by the server. I think the privacy notice should make some (possibly vague) reference to the data being encrypted.

**Comment by shane-tomlinson** [comment]
@davismtl is taking this up with somebody, possibly legal, possibly product.

**Comment by davismtl** [comment]
I have a meeting with legal on July 20th.

**Comment by davismtl** [comment]
Met with legal. They are adding a mention to their next privacy policy update. I have a meeting to follow up next week with them.

**Comment by vladikoff** [comment]
blocked by legal doc updates
