### ISSUE TITLE
FxA authentication should not immediately redirect back to Sync prefs [bz1289480]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#181]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1289480

Created attachment 8774771
verify.png

Currently when users create a Firefox Account to Sync in iOS, they are immediately returned to the Sync prefs with "Verify your email address" in black type beneath the email.

We will soon be turning on sign-in confirmation for all accounts where all Sync sign-ins with require email verification. We would like to keep everyone alive through this difficult journey. It presents a page much like the Confirm your account screen.

Some improvements:
1. This copy should probably match the colour of the Log out button below.
2. The user should have to manually exit this screen. It should not auto-return.

**Comment by vladikoff** [comment]
from mtg: not clear which path to take here yet, fix content server or fix iOS

**Comment by vladikoff** [comment]
@ryanfeeley to figure some of it out  :)

**Comment by vbudhram** [comment]
First part of this was merged https://github.com/mozilla/fxa-content-server/pull/4089

**Comment by rfk** [comment]
Phase 1 done; backlogging phase 2 of this for now
