### ISSUE TITLE
Wrong language of Getting Started with Sync [bz1041130]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#182]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1041130

User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:30.0) Gecko/20100101 Firefox/30.0 (Beta/Release)
Build ID: 20140605174243

Steps to reproduce:

Menu bar > Menu > Sync (for the first time)

My location: The Netherlands
Firefox UI language: English
OS: Windows 8.1 (selected language: English)

Actual results:

The Get Started page of Sync appeared in Dutch, including a link to Sync conditions in Dutch.

Expected results:

1) The Get Started page should appear in English, because this is the selected UI language for Firefox.
2) There is no language select possibility on the page.
Apparently, the browser location (Netherlands) is used to select the language, but it is better to a) follow the UI language setting, b) to take the local language of the browser location.

**Comment by shane-tomlinson** [comment]
It seems to me this is an issue with the browser since "Get Started" is in the "about:accounts" content, which is hosted by the browser.
