### ISSUE TITLE
accounts.firefox.com CSP prevents loading of necessary resources from accounts.cdn.mozilla.net [bz1294559]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#183]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1294559

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0
Build ID: 20160726073904

Steps to reproduce:

Tried to set up a new Firefox Sync account in Firefox 48.0 on Mac OS X 10.11.6, first with menu items then by visiting https://accounts.firefox.com/signup

"Accept third-party cookies" is set to "Always"

Actual results:

In both cases, what should have been the sign up page was blank.  at https://accounts.firefox.com/signup, this was in the console:

---------- ----------
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://accounts.firefox.com 'unsafe-eval' https://accounts.cdn.mozilla.net").
	

window.oldSetTimeout=window.setTimeout;...

privacy (line 1)
Content Security Policy: The page's settings observed the loading of a resource at self ("script-src https://accounts.firefox.com https://accounts.cdn.mozilla.net"). A CSP report is being sent.
	

window.oldSetTimeout=window.setTimeout;...

privacy (line 1)
---------- ----------

After seeing the console messages, I tried to see if I could sign up by visiting https://accounts.cdn.mozilla.net/signup directly.  This time the form appeared, but could not be submitted due to "Unexpected error".  After attempting to submit, this was in the console:
---------- ----------
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://accounts.cdn.mozilla.net 'unsafe-eval' https://accounts.cdn.mozilla.net").
	

window.oldSetTimeout=window.setTimeout;...

signup (line 1)
Content Security Policy: The page's settings observed the loading of a resource at self ("script-src https://accounts.cdn.mozilla.net https://accounts.cdn.mozilla.net"). A CSP report is being sent.
	

window.oldSetTimeout=window.setTimeout;...

signup (line 1)
"NetworkError: 403 Forbidden - https://accounts.cdn.mozilla.net/_/csp-violation"
csp-violation
"NetworkError: 403 Forbidden - https://accounts.cdn.mozilla.net/_/csp-violation-report-only"
csp-vio...rt-only

             _.-~-.
           7''  Q..\
        _7         (_
      _7  _/    _q.  /
    _7 . ___  /VVvv-'_                                            .
   7/ / /~- \_\\      '-._     .-'                      /       //
  ./ ( /-~-/||'=.__  '::. '-~'' {             ___   /  //     ./{
 V   V-~-~| ||   __''_   ':::.   ''~-~.___.-'' _/  // / {_   /  {  /
  VV/-~-~-|/ \ .'__'. '.    '::                     _ _ _        ''.
  / /~~~~||VVV/ /  \ )  \        _ __ ___   ___ ___(_) | | __ _   .::'
 / (~-~-~\\.-' /    \'   \::::. | '_ ` _ \ / _ \_  / | | |/ _` | :::'
/..\    /..\__/      '     '::: | | | | | | (_) / /| | | | (_| | ::'
vVVv    vVVv                 ': |_| |_| |_|\___/___|_|_|_|\__,_| ''

Hi there, nice to meet you!

Interested in having a direct impact on hundreds of millions of users? Join
Mozilla, and become part of a global community that’s helping to build a
brighter future for the Web.

Visit https://careers.mozilla.org to learn about our current job openings.
Visit https://www.mozilla.org/contribute for more ways to get involved and
help support Mozilla.

---

If you don't want to see this message next time, run this JS statement:

    easterEgg.disableEasterEgg()

ef0d0f59.main.js (line 34)
GET https://accounts.cdn.mozilla.net/config
	
304 Not Modified
		514ms	
ef0d0f59.main.js (line 16)
GET https://accounts.cdn.mozilla.net/i18n/client.json
	
304 Not Modified
		88ms	
ef0d0f59.main.js (line 16)
Unexpected error
	

ef0d0f59.main.js (line 17)
"NetworkError: 403 Forbidden - https://accounts.cdn.mozilla.net/metrics"
metrics
---------- ----------

Expected results:

I should have seen the form at https://accounts.firefox.com/signup, and submitting it should have worked.

**Comment by philbooth** [comment]
@shane-tomlinson, we figured you might be the person who knows most about this?

**Comment by rfk** [comment]
This turned out to be a bad interaction with an addon.
