### ISSUE TITLE
Verified email shows up as unverified. cannot sync. [bz1293742]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#186]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1293742

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0
Build ID: 20160726073904

Steps to reproduce:
1. Install Firefox
2. login with my existing email and password
3. message pops up saying I need to verify a new email (it is not a new email, it is the same email I have been using)
4. Never receive the email
5. Hit resend
6. Repeat 5
7. Repeat 5
8. Repeat 5
9. Too many attempts message.

Actual results:
1. Firefox tries to verify an email that is already existing in the system, therefore no email is sent out to that email to verify.
2. prevents user from syncing their data to new browser

Expected results:
1. After typing me email and password, I should be let in because the email and password were correct and already into the system
2. Firefox should not have to verify the email because it is not new.
3. Firefox should start syncing my data

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1293742#c7
