### ISSUE TITLE
Some strings are displayed unlocalized [bz1301873]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#190]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1301873

Created attachment 8790016
openGmail.png

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
Build ID: 20160728204513

Steps to reproduce:

1) Clicked "login button" on about:preferences?entrypoint=menupanel#sync
2) Filled in credentials

Actual results:

A page asking me for confirming my email was show with button in English instead of my locale (cs). Also, in the email sent in this step is one unlocalized string. (see attachments)

Expected results:

All strings should be localized. 

They are translated for quite a long time on Pontoon, not sure if it is synced with repo correctly 

https://pontoon.mozilla.org/cs/firefox-accounts/all-resources/?string=154325
https://pontoon.mozilla.org/cs/firefox-accounts/all-resources/?search=open

**Comment by shane-tomlinson** [comment]
Partial dup of https://github.com/mozilla/fxa-content-server/issues/4158, and the auth mailer I think we may have had old dependencies - https://github.com/mozilla/fxa-auth-mailer/issues/210.

Keeping this open to check cs email translations when train-70 goes out.

**Comment by shane-tomlinson** [comment]
The email string is localized for Czech on prod in train-69:

<img width="330" alt="screen shot 2016-09-19 at 22 19 06" src="https://cloud.githubusercontent.com/assets/848085/18649409/3fa45a9e-7eb7-11e6-9989-8e977cdf4e92.png">

Closing as "we're on the case"
