### ISSUE TITLE
Broken session management in accounts.firefox.com All integrations [bz1178634]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#199]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1178634

User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36 OPR/27.0.1689.76

Steps to reproduce:

Go to accounts.firefox.com
Login
Then go to any firefox accounts integration sites such as marketplace.firefox.com
Login using 0auth

Now from firefox accounts change the password, 
The session would not be invalidated from marketplace.firefox.com

Actual results:

This is a broken session management flaw which can allow account takeover if the session management is not handled. The session was not invalidated in the integration site

Expected results:

The session should have been invalidated in the integration site

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1178634#c7
