### ISSUE TITLE
accounts.firefox.com/contribute.json [bz1185016]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#200]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1185016

I was on https://accounts.firefox.com/settings and wanted to find out where I can file bugs or which IRC channel people hang out on. I tried going to https://accounts.firefox.com/contribute.json but it 404'ed. 

You can read more about the contribute.json project on https://contribute.paas.allizom.org/
(soon to be replaced with www.contributejson.org)

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1185016#c1
