### ISSUE TITLE
Some French users don't receive the confirmation email from Sync to their email address @free.fr [bz1320501]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#223]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1320501

On the French community board, some users reported they don't receive the confirmation email sent by Sync to their email address @free.fr (Free is a known French ISP).

Reports:
https://forums.mozfr.org/viewtopic.php?f=5&t=131636
https://forums.mozfr.org/viewtopic.php?f=5&t=131680

Is it possible the Sync service is blocking this ISP? Issue with FF50?

**Comment by vladikoff** [comment]
cc @jrgm

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1320501#c6
