### ISSUE TITLE
Sync Sign In button gets disabled on failure [bz1323934]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#224]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1323934

Created attachment 8819207
After Sign in failure.png

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:50.0) Gecko/20100101 Firefox/50.0
Build ID: 20161208153507

Steps to reproduce:

If sync login fails, either when internet connection is slow or if the host is slow to respond, the Sync "Sign in" button cannot be tapped again to reattempt since it's disabled after the failed sign in attempt. 

To simulate:
1. Enter your Firefox Sync Account credentials (but, don't tap the sign in button yet)
2. Turn off your internet
3. Now, tap the "Sign in" button.

Actual results:

The "Sign in" button gets disabled immediately. After "working" for some time, the message "Unexpected error" is displayed. The "Sign in" button remains disabled. So, if you want to enabled to tap it again, you'd have to delete a character or so of your password. See screenshot.

Expected results:

The "Sign in" button should get enabled after the failed attempt to sign in.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1323934#c4
