### ISSUE TITLE
Adjust RTL for the "Devices & apps" part [bz1324832]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#225]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1324832

Created attachment 8820345
Devices and apps

Current view of the Devices & apps section makes most of the text in it to be overlapped by the "Disconnect..." button in RTL builds.

See attached screenshot.

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/pull/4589
