### ISSUE TITLE
Delete account is too simple [bz1325998]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#226]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1325998

Created attachment 8822108
delete account

User delete Firefox account is too simple if he let Firefox remember the password of it. Just a click on "Delete account" and it was done. Maybe we should add an E-mail verification before delete.

**Comment by vladikoff** [comment]
from meeting: closing as wontfix after talking to dev and ux teams
