### ISSUE TITLE
FxA pages are not served in the right language for several locales [bz1329172]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#227]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1329172

[Affected versions]:
Firefox 53.0a1 (2017-01-05)
Firefox 52.0a2 (2017-01-05)
Firefox 51.0b12 (20170105155013)
Firefox 50.0.1 (20161208153507)

[Affected platforms]:
Windows 10 64-bit
Ubuntu 16.04 32-bit

[Steps to reproduce]:
1.Launch Firefox with a clean profile using one of the following locales: el, eu, ga-IE, gu-IN, xh, eo, vi.
2.Go to Panel Menu [≡] → Sign in to sync and choose to create a new Firefox account or login using an existing one.
3.Check the page language. 

[Expected Results]:
FxA Sign In / Create a FxA page is successfully served in the right locale.

[Actual Results]:
- FxA Sign In and Create a FxA pages are not translated in the right locale.
- See screenshots: http://screencast.com/t/rMB1aFRr ,  http://screencast.com/t/SfLAW97n3bp

**Comment by shane-tomlinson** [comment]
From https://pontoon.mozilla.org/projects/firefox-accounts/:

- el is 64% translated
- eu is 50%
- ga-IE not in the list.
- gu-IN not in the list
- eo not in the list
- xh not in the list
- vi not in the list.

**Comment by shane-tomlinson** [comment]
Closing as WONTFIX, all the mentioned locales are either not translated at all, or not at a sufficiently high level of translation.
