### ISSUE TITLE
User takes long time to receive certification mail [bz1332140]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#229]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1332140

An user in Taiwan complains about he uses hotmail to login to Firefox Sync service, but it takes more than 8 hours to receive the certification mail, and this mail is in spam mail.

How could we help this user to know why it takes long to receive mail and could we improve the experience not see the mail in spam mail?

**Comment by shane-tomlinson** [comment]
Ref #250

**Comment by vladikoff** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1332140#c2
