### ISSUE TITLE
304 responses include a content-type header. [bz1332992]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#231]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1332992

A conditional request to https://profile.accounts.firefox.com/v1/profile returns a 304 with "Content-Type: application/json; charset=utf-8" but an empty body. This causes devtools to apparently get a little upset trying to parse the empty payload as JSON (saying it is invalid). If you squint a little, you could take https://tools.ietf.org/html/rfc7232#section-4.1 as saying this header SHOULD NOT be included.

Probably not a big deal and possibly could be argued it's more a devtools bug, but I can't see a reason the header should be included, so opened this bug. Your welcome ;)

**Comment by vladikoff** [comment]
Closed as WONTFIX, see https://bugzilla.mozilla.org/show_bug.cgi?id=1332992#c2
