### ISSUE TITLE
Unable to change email address for Firefox Account [bz1334107]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#235]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1334107

Created attachment 8830714
Screen Shot 2017-01-26 at 7.53.00 AM.png

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:51.0) Gecko/20100101 Firefox/51.0
Build ID: 20170118123726

Steps to reproduce:

1. Log into Firefox Account for access to my Add-Ons Developer profile. (https://addons.mozilla.org/en-US/firefox/users/edit). Use email address and password. 
2. Arrive at my Add-Ons profile page. 
3. Under the email field a message reads "Firefox Accounts users cannot currently change their email address." The email field is disabled from editing. 

Actual results:

Email field has a message that reads "Firefox Accounts users cannot currently change their email address." I am unable to select the email field for editing the email address. 

Expected results:

I need to change my email address. The email account I am currently using will be defunct by the end of April. 

As alternative, there should be an account retrieval mechanism in the event of defunct email addresses. For example, have a secondary email address as a backup.

**Comment by vladikoff** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1334107#c4
