### ISSUE TITLE
The first run page needs to know if someone has entered a username or password [bz1338350]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#239]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1338350

Created attachment 8835760
skip-setup.png

On the new firstrun page that we built for our onboarding experiment - 
https://www.mozilla.org/en-US/firefox/51.0.1/firstrun/?f=99
https://www.mozilla.org/en-US/firefox/51.0.1/firstrun/?f=100

We've included a skip button. The skip button should get grayed out when someone starts to enter their credentials. Erica (who built the page) said we need a message back from the form in order to make that happen. Without this, we don't know if we can gray out the skip button so it stays active and that leads to a situation where the user could start to sign in or create an account and then choose to "skip the step" that they are on, effectively canceling the operation.

We are about to run a few hundred thousand people through this so we should fix this as soon as possible.

**Comment by vladikoff** [comment]
Fixed, see https://bugzilla.mozilla.org/show_bug.cgi?id=1338350
