### ISSUE TITLE
account confirmation email not received [bz1339743]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#240]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1339743

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
Build ID: 20170125094131
Firefox for Android

Steps to reproduce:

After creating an account for Syncing operation between my peripherals I never receive the mail needs for account confirmation despite many tries.
I have applied all the procedures you gave in the Help information  whithout any success.
Account information used : dsantacroce@orange.fr / dsanta13170
Thank you for your help
PS: The problem occurs on PC, Tablet and phone

**Comment by shane-tomlinson** [comment]
We have a general email deliverability feature ongoing, which should cover this. Closing this particular problem.
