### ISSUE TITLE
Firefox account: impossible to verify the account. The confirmation e-mail is never recieved. [bz1347138]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#252]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1347138

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0
Build ID: 20170125094131

Steps to reproduce:

I have resetted my Android Lolliop terminal to the factory settings. I have veried that I am able to recieve the message in K9-Mail. 
I need to configure my Firefox sync account.
- I go to Settings.
- I go to Acccount.
- I select "Se connecter" (Log in).
- A page "Créer un compte Firefox" (Create a Firefox account) is displayed.
- I click on the link: "Vous possédez déjà un compte ? Connectez-vous" (You already have got an account ? Log in".
- A page "Connexion" (Connexion) is displayed.
- I enter my e-mail and my password. I press on the "Connexion" (Connection) button.
- A page "Confirmer cette connexion" (Confirm this connection" is displayed. A message "Pour plus de sécurity renforcée de nos données Firefox, nous avons envoyé un message de confirmation à {{my e-mail address}}" (For an enhanced security of our Firefox datas, we have sent a confirmation message to {{my e-amil address}}. 
- I  never recieve the confirmation e-mail.

I click on the hyperlink "Le message n'est pas arrivé et ne se trouve pas dans les indésirables ? Renvoyez le" (The message is not arrived and is not in the spam? Send it again). 
- The message in the red background "Courriel envoyé" (e-mail sent) is displayed.
- I  never recieve the confirmation e-mail.

Actual results:

I never recieve the confirmation message in my K9-Mail client. It is not in the inbox or in the spam folders.

Expected results:

I should have received the confirmation e-mail.
I can not synchronize my bookmarks, my add ons. This is very annoying.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1347138#c3
