### ISSUE TITLE
[I18n] CJK characters in Device names are displayed as "?" in Devices & apps [bz1348298]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#253]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1348298

STR:
1. Connect Firefox to Firefox Accounts, both desktop and mobile is effected.
2. Change device name in Firefox Settings to include CJK character, for example: 
"Peter 在 petercpg-home 上的 Nightly"
3. Wait couple seconds to let it sync
4. Open https://accounts.firefox.com/settings/clients, and login.
5. Observe the "Devices & apps" section.

Expected:
The device name set in Firefox Settings is displayed, no mojibake or mis-encoded characters. In this testcase: "Peter 在 petercpg-home 上的 Nightly"

Actual:
CJK characters are displayed as "?", e.g., "Peter ? petercpg-home ?? Nightly"

**Comment by rfk** [comment]
Duping to https://github.com/mozilla/fxa-auth-db-mysql/issues/229 (which I've noted in bugzilla, hopefully the bug mirroring script does not resurrect this issue)
