### ISSUE TITLE
Unable to use signin page - accounts.firefox.com [bz1348681]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#254]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1348681

User Agent: Mozilla/5.0 (Windows NT 5.1; rv:25.0) Gecko/20100101 Firefox/25.0
Build ID: 20131112160018

Steps to reproduce:

On page https://addons.mozilla.org/en-US/firefox/ choose login link

Actual results:

Page https://oauth.accounts.firefox.com/v1/authorization?action=signin&scope=profile... fails to load

Expected results:

Prompted to sign in and so I can see my profile on addons.mozilla.org

**Comment by shane-tomlinson** [comment]
I tested in Fx 25 w/o a problem.

**Comment by shane-tomlinson** [comment]
Backlogging until we have more info, I had no problems w/ fx 25.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1348681#a6137513_481559
