### ISSUE TITLE
Add Deep Linking into FxA Views and Prefill Forms [bz1317580]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#261]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1317580

This is a feature request to add additional deep linking capabilities into FxiOS, in support of Firefox accounts.

Specifically, we should add the capability to directly launch into the FxA Sign-in view controller and prefill the login form with the passed email/code. We should also be able to reuse the existing deep linking scheme `firefox://`.

The extended scheme could look like below.

firefox://fxa=signin

The user is taken directly to the FxA Sign-in page. If param email/code is passed, then the email field on the page will be prefilled. Ex. firefox://fxa=signin&email=old@email.com&code=coder. After the page has been loaded, we could inject the javascript needed to fill out these input fields.

firefox://fxa=signup

The user is taken directly to the FxA Sign-up page and email field is prefilled. Ex. firefox://fxa=signup&email=new@email.com

In the event of an error while navigating or filling out the page, the current default action will be taken, which is to open the app.

Adding these capabilities will allow FxA to reduce the friction for signing up and signing in users.

Thoughts?

**Comment by vladikoff** [comment]
from mtg: @rfk to push this forward
