### ISSUE TITLE
Add Deep Linking into FxA and Prefill login Forms [bz1356386]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#262]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1356386

This is a feature request to add additional deep linking capabilities into android, in support of Firefox accounts.

Propose deeplinking scheme

firefox://fxa-signin?signin=<token>

After clicking this link, Firefox for android app opens and loads a view containing the FxA sign-in page. The page is loaded with the `signin=<token>` query parameter in the url.

The plan is to have FxA sign-in page read the query paramater and get the correspond user information and prefill the login forms.

**Comment by vladikoff** [comment]
from mtg: Setting P1, at least need to figure it out

**Comment by vladikoff** [comment]
from mtg:  waiting for the patch to land to fix deep linking in android. 

@rfk to poke the Android team

**Comment by vladikoff** [comment]
waiting for merge , will need to figure out how to test this
