### ISSUE TITLE
Send deleted account events (FXA_IDs) to basket + salesforce [bz1358123]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#263]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1358123

When a Firefox Account user deletes their account, we do not apparently have a way to inform salesforce of this deletion. 

If someone deletes their account, we don't want to send them anymore emails about their account.

We need to create a mechanism on an ongoing basis, to either remove deleted account data from SFMC or to create a master exclusion list that prevents us from sending to a deleted account user. 

Two possibilities: 

Set up the logic to consume "account deleted" events on an ongoing basis.
* Do a one-off comparison of the FxA uids in salesforce vs those in
the accounts db, and delete any from the former that are no longer in
the later.

 We could then use that as an exclusion list for any email sends that go to
> accounts.

An alternative could be to ask FxA about each user before you send
them an email, but that sounds pretty awful to do at volume.

**Comment by shane-tomlinson** [comment]
@rfk - can you triage this? We are backlogging it for now, you can promote if it needs to be prioritized.

**Comment by rfk** [comment]
This is being deployed on the basket side, blocked on confirmation from them whether it's working as intended.

**Comment by rfk** [comment]
this is now up  and running!

**Comment by vladikoff** [comment]
Yay!
