### ISSUE TITLE
Look into identity api with fxa backend [bz1320862]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#265]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1320862

We've implemented launchWebAuthFlow and getRedirectURL support for general oauth dialogs.  We could consider using the google specific parts of the API (the rest) backended by fxa.

**Comment by vladikoff** [comment]
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1320862#c16
