### ISSUE TITLE
Wrong error when dom.storage.enabled is false [bz1360691]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#267]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1360691

1. Have "dom.storage.enabled" false
2. Visit accounts.firefox.com
3. Will be redirected to cookies_disabled screen
4. Click on the retry button
5. The message is "Cookies are still disabled" while in fact the local/sesiosStorage is disabled

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1360691#c3
