### ISSUE TITLE
sync: Missing or duplicate items? link does nothing when iframed in mozilla.org [bz1360126]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#268]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1360126

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Build ID: 20170307221322

Steps to reproduce:

Entered https://www.mozilla.org/en-US/firefox/accounts/ and was correctly recognized.
Could navigate the tabs all right.

Actual results:

But after opening the tab 
"Devices & apps", the link "Missing or duplicate items?" would not work. I clicked and waited for minutes.  Clicked again... No effect, just nothing

Expected results:

That link is supposed to allow one to change the list of synced devices/applications.
I find this a grave functionality bug of the sync feature.

**Comment by vladikoff** [comment]
this should open a new tab...
