### ISSUE TITLE
Sync - confirmation email for new device [bz1357192]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#269]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1357192

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Build ID: 20170330194312

Steps to reproduce:

add a new device to sync my account

Actual results:

Every time I add a new device, I have to confirm it via a link send by email. But my email provider uses grey listing and the mail arrives days later or never. This is really annoying. The reason is, you use every time another client to send the mail.

Expected results:

I have three different solutions in my mind.
1. Just use the same client and sender to send the confirmation email again. This reduces massive the time to receive the confirmation mail, but it is still annoying.
2. Just send an informational email to the email address.
3. Switch it off completely 
May you can make it configurable. I do not sync any passwords, so I do not need this security level at all.

**Comment by vladikoff** [comment]
cc @rfk , can we close this at some point? 

> from triage
