### ISSUE TITLE
Softvision Testing Request for FxA Feature: Add a Secondary Email [bz1361571]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#270]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1361571

Created attachment 8863945
This is the zip file needed to set up the custom test environment.

The FxA team has developed a new feature to add a secondary email to a Fx Account, and it's ready for testing by softvision.

Feature description:  This feature plans to prevent users from being locked out of their Fx accounts and Sync data by allowing them to add a second email to their account. Multiple phases are envisioned for this feature. The engineering team has developed functionality described in phase 1 described in the feature doc. The other phases are still under consideration so expect the feature doc. to be updated.

Feature doc: https://docs.google.com/document/d/1DOUWRbxU8ah6AL3gUTrlYKFY42jt_czOHbu4wL4E-sc/edit

Proposed/preliminary test plan: https://docs.google.com/spreadsheets/d/1bR1agEpzdbWhsTDrfOaAIdbY6IOP-_c9WauW75VJxZc/edit#gid=0

Environment in which to test: Please use the following instructions to set up a custom test environment.

   1) Rename user.js.piz file to user.js.zip and extract the `user.js` file.
   2) On windows goto %APPDATA%/Mozilla/Firefox/Profiles
   3) Copy the `user.js` file into the .default profile
   4) Launch Firefox
   5) Confirm settings by going to `about:config` and searching for `fxa`. You should see urls configured to point to emails3 instead of accounts.firefox.com

Devices to test with: desktop, android, ios

Need testing completed by: May 9th?

Will the feature ride Fx train? Yes, train-87

Will there be any automation test covered by the developer(s): No
   If yes, link to automation test suite:  N/A 

Risk Analysis (concerns about any functionality it touches that might require more in depth testing: the registration and password-reset flows

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1361571#c7
