### ISSUE TITLE
Sign-in unblock code is not sent to secondary email [bz1362218]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#271]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1362218

STR:
1. Create and verify account A with email X (with pattern 'block.[your_choice]@restmail.net). 

[Note: To check `@restmail.net`, go to http://restmail.net/mail/block.[YOUR_CHOICE]. This outputs JSON Array and most recent message is at the bottom.]

2. Add and verify secondary email X2 (with pattern 'block.[your_choice]@restmail.net) to A.
3. Log out from account A.
4. Sign back in to account A with email X.
5. Need authorization code to sign in.
6. Go to http://restmail.net/mail/block.[your_chice from email X] and look for unblock code in JSON output
7. Go to http://restmail.net/mail/block.[your_chice from email X2] and look for unblock code in JSON output

Expected: Both email X (Primary email)and X2 (Secondary email) should get unblock code. 

Actual: Only primary email (X) gets unblock code.

Please see this video: https://ranisharma22.tinytake.com/sf/MTU3NTEzNl81NDAyNzA2

**Comment by vladikoff** [comment]
Fixed!
