### ISSUE TITLE
Allow stage and dev autopush servers to be used on dev and stage FxA servers. [bz1362979]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#274]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1362979

For dev and stage FxA servers, it has been impossible to use dev and stage autopush servers because allowedServerRegex restricts them.

Please could you add 

https:\/\/[a-z.-]+.mozaws.net 

pattern to allowedServerRegex to allow this.  

https://github.com/mozilla/fxa-auth-server/blob/c0228b5b0e46a192eb8c75fc1dae4e4ac100bc1d/config/index.js#L680

**Comment by vladikoff** [comment]
Ref: https://github.com/mozilla/fxa-auth-server/issues/1799

**Comment by vladikoff** [comment]
Fixed in auth-server
