### ISSUE TITLE
Unverified secondary email of one account doesn't get added to other Fx account as secondary email [bz1363470]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#275]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1363470

STR:
1. Launch Firefox.
2. Create Firefox account A with email X and verify the account.
3. Enter email X1 in secondary email field and press add button.
4. Don't verify the secondary email X1.
5. Create another Firefox account B with email Y and verify the account.
6. In secondary email field in account B enter email X1 and press add button.

Expected: Unverified secondary email of one account should be available for other account's secondary email as per specification. Verification email sent /verification required should appeared.

Actual: Error message "This email was already verified by another user" displayed, even though secondary email X1 was not verified with account A.

**Comment by vladikoff** [comment]
@vbudhram https://bugzilla.mozilla.org/show_bug.cgi?id=1363470 still open

**Comment by vbudhram** [comment]
I spoke to soon, this is a completely different issue from what I originally thought (account created from unverified secondary email address). Created https://github.com/mozilla/fxa-auth-server/pull/1892 to fix this.
