### ISSUE TITLE
[fxa][Staging 83] Confirmation email not expired after an hour [bz1351648]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#280]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1351648

Device: HTC Desire 820 (Android 6.0.1), Huawei MediaPad M2 (Android 5.1.1)
Environment: Staging server [Train 83]

Steps to reproduce:

1. Go to any Create account form;
2. Follow the steps for creating and tap on "Save settings";
3. Wait an hour and after that go to mail and tap on verification link.

Actual result: 
After step 2, an email to confirm the account is send.
After step 3 the confirmation email expires.

Expected results:
After step 3 the link from mail confirms the sign-in. The link wasn't expired.

Notes: is the user taps on "Back. Didn't arrive and not in spam folder? Resend" and in mail are two verification links, both are working.

**Comment by philbooth** [comment]
@rfk, in triage we think this is the expected behaviour. Are we okay to close it?

**Comment by vladikoff** [comment]
@rfk, see above ^
