### ISSUE TITLE
Some SVG device icons will not load [bz1365996]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#281]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1365996

Noticed that the Android tablet icon would not load.

Reference Github issue: https://waffle.io/mozilla/fxa/cards/591c6d197bb5a701a9479b06

Softvision, could you please conduct some testing around this to see if you can reproduce the problem and report back any results?

**Comment by vladikoff** [comment]
This was fixed
