### ISSUE TITLE
first run page has unstyled fx accounts login form [bz1368404]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#283]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1368404

Created attachment 8872234
Screen Shot 2017-05-29 at 12.26.55.png

53.0.3 (64-bit)

STR:

1. create new profile
2. wait for first-run page to load

Expected: accounts login form is styled

Actual: it is not styled

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1368404#c14
