### ISSUE TITLE
Cannot login to sync from any device, even newly installed. Always get red bar with message "Your email was just returned" [bz1369378]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#284]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1369378

Created attachment 8873403
firefox_sync_login_failed.png

open Login-dialog for Sync. Entered E-Mail-address and valid password. Clicked "Login"

This happens on any device on any Firefox-Version

Red Bar with text "Your email was just returned" appears

Login should be completed and syncing should have started

**Comment by vladikoff** [comment]
@rfk could you please triage this one, setting to active for now

**Comment by vladikoff** [comment]
@rfk to close this...
