### ISSUE TITLE
Look at the page, the text "Terms of service" or "Умови надання послуг" is written on different languages (english and ukrainian) [bz1375433]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#292]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1375433

Created attachment 8880296
Умови надання послуг1.bmp

User Agent: Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0
Build ID: 20170607123825

Steps to reproduce:

1) open Firefox version for Ukraine (firefox setup 52.2.0esr.exe)
2) click on the menu in the upper right corner
3) go to "відкрити налаштування Синхронізації"
4) click the icon "Умови використання"
5) look at the page, the "text of service" is written on different languages (english and ukrainian)

Actual results:

the text "Terms of service" is written on different languages (english and ukrainian)

Expected results:

the text "Terms of service" or "Умови надання послуг" is not written on different languages (english and ukrainian)

**Comment by juliemccracken** [comment]
Have made an inquiry to find out if this translation is desired by legal and if so, who will do it.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1375433#c2
