### ISSUE TITLE
the text "Privacy Notice" or "Приватна інформація" is  written on different languages (english and ukrainian) [bz1375441]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#293]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1375441

Created attachment 8880304
Повідомлення про приватність.bmp

User Agent: Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0
Build ID: 20170607123825

Steps to reproduce:

1) open Firefox version for Ukraine (firefox setup 52.2.0esr.exe)
2) click on the menu in the upper right corner
3) go to "відкрити налаштування Синхронізації"
4) click on the icon "Повідомлення про приватність"
5) look at the page, the text "Privacy Notice" or "Приватна інформація" is in written on different languages (english and ukrainian)

Actual results:

the text "Privacy Notice" or "Приватна інформація" is  written on different languages (english and ukrainian)

Expected results:

the text "Privacy Notice" or "Приватна інформація" is not  written on different languages (english and ukrainian)

**Comment by juliemccracken** [comment]
I'm in the process of finding out who this would be.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1375441#c5
