### ISSUE TITLE
Specific email not receiving emails investigation blue.heron3@verizon.net [bz1376005]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#294]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1376005

User: blue.heron3@verizon.net has emailed guigs directly asking for help with an email for a Sync account. 

The user has tried the following:
*"re-installed Windows and then Firefox on my Windows 10 computer. I've had a Firefox account for a year or so and wanted to sync with it. 
*I clicked 'Verify Email' in order to do that. Firefox indicates that it sent the email, but I never get it.
* Nothing in my junk or spam folders. It's been an entire day since my initial attempt, and I've tried several times subsequently but I get no email. "

I verified with the user that their email is indeed working. 

Can we investigate on our side what might be happening?

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1376005#a17214841_481559
