### ISSUE TITLE
Add a Firefox Accounts Verify Login Push Notification to Android [bz1377917]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#295]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1377917

We want to add the ability for already signed-in Firefoxes to be usable in a 2FA fashion for signing in to new devices, as described in this document: https://docs.google.com/document/u/1/d/16fdARc6MC9XO7FBG9YJ4bpeqhHcv1G3ua0uzeS4EckY/edit

- We want to handle the "fxaccounts:verify_login" command in here: https://dxr.mozilla.org/mozilla-central/source/mobile/android/services/src/main/java/org/mozilla/gecko/fxa/FxAccountPushHandler.java#48
- To start with, this can simply be another method at the bottom of the file.
- This needs to show a notification, using the title, text, and URL from the incoming JSONObject 'data'.
- An example of how to show a notification can be found here: https://dxr.mozilla.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/tabqueue/TabReceivedService.java#59-82
- After the notification is figured out, there's another state we want to handle, perhaps we can ask Grisha about when we get there. If Firefox is already open when the notification is received, we want to open the tab directly.

**Comment by vladikoff** [comment]
from mtg: blocked on Android feedback

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1377917#a35839901_481559
