### ISSUE TITLE
SAUCE lab username and access token & Coveralls_Repo_Token Leakage [bz1374071]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#297]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1374071

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

Steps to reproduce:

I look out in all the products on TRAVIS CI build logs and found that your SAUCE-LAB User-name and Access-Token is leaked as well as Coveralls Repo Token also leaked.

Sauce-lab User-name and Access-Token is leaked in Travis CI build logs of " fxa-js-client " product at line L269 URL (https://travis-ci.org/mozilla/fxa-js-client/jobs/238861144#L269).

This can be used to perform every API calls of sauce-lab.(e.g Creating a Sub account).

Coveralls Repo Token is leaked Travis CI build logs of 3 products.

1.) browserid-local-verify Line L618 URL (https://travis-ci.org/mozilla/browserid-local-verify/jobs/166864061#L618)

2.) fxa-auth-mailer Line L405 URL (https://travis-ci.org/mozilla/fxa-auth-mailer/jobs/226116130#L405)

3.) fxa-customs-server Line L162 URL (https://travis-ci.org/mozilla/fxa-customs-server/jobs/237771360#L162).

FIX:
You should revoke the access_key and secure the key in Travis Cl build logs.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1374071#c3
