### ISSUE TITLE
Can we provide an activity page on the sync client? [bz578395]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#3]
From https://bugzilla.mozilla.org/show_bug.cgi?id=578395

It would be nice if we gave the user recent activity from all clients in a single view and provided the client type and ip address with geo information.

**Comment by vladikoff** [comment]
@rfk should we move this to fxa-features?

**Comment by rfk** [comment]
Yes, although this one in particular is so old and vague that I'm just going to close it out, I don't think there's useful content to migrate to the features board.
