### ISSUE TITLE
Implement multi-factor authentication on Firefox Accounts (MFA/2FA) [bz1379677]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#300]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1379677

Firefox Accounts should implement support for authentication via multiple factors. Ideally, the user has the ability to add as many factors as supported by the service, and not be limited to two.

TOTP is probably the easiest and most standard second-factor.
U2F/Fido is also a strong candidate.
SMS must not be implemented, as SIM takeover is a real problem.

See also https://pages.nist.gov/800-63-3/sp800-63b.html

**Comment by banool** [comment]
Any progress on this? Was just about to make the move to firefox full time as a browser but this is a huge missing feature.

**Comment by vladikoff** [comment]
> Any progress on this?

This is on the roadmap for Q1 2018

**Comment by vladikoff** [comment]
@ryanfeeley should we start UXing this? Hopefully that will speed this up. Do we have any older 2FA diagrams that we made with Sai?

**Comment by vladikoff** [comment]
@ryanfeeley for next train to start UXing

**Comment by vladikoff** [comment]
from mtg: @rfk to close this

**Comment by rfk** [comment]
I'm going to close this "meta-bug" in favour of the concrete implementation issues in our TOTP milestone:

  https://waffle.io/mozilla/fxa?milestone=FxA-143:%20MFA
