### ISSUE TITLE
Your email was just returned [bz1381832]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#305]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1381832

User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Build ID: 20170628075643

Steps to reproduce:

I tired to reset my Firefox Sync password, using the same email as this Bugzilla account.

Actual results:

I receive the message "Your email was just returned" and further action is blocked.

Expected results:

This is my primary email address which I use on a daily basis. I have never had an issue with this email address

**Comment by shane-tomlinson** [comment]
@jbuck and @rfk - can you triage this?
