### ISSUE TITLE
Firefox should automatically disconnect when FxA is deleted [bz1279333]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#307]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1279333

Created attachment 8761799
disconnect-fxa.png

When a Firefox Account is deleted, Firefox for iOS should simply be signed out of Sync.

You can optionally include a notification stating:

Sync disconnected because the Firefox Account used was deleted.

Tapping the notification could bring the user to sync prefs.

**Comment by vladikoff** [comment]
> rfk added the waffle:next  label 23 hours ago

You re-added this to `next`, do we want to fix this?

**Comment by vladikoff** [comment]
Removed FxA Whiteboard, let me know if we want to invest this again
