### ISSUE TITLE
Devices from previous account appearing in Send Tab [bz1291831]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#309]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1291831

STEPS TO REPRODUCE
1. Set up a multiple-device Sync constellation with at least one iOS device
2. Send a tab from iOS device to any other device
3. At the bottom of Firefox iOS settings, click Log Out
4. Log in to a different account with multiple devices

EXPECTED RESULTS
- New devices appear and can be sent tabs

ACTUAL RESULTS
- Previous devices appear, but any sent tabs fail to appear

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1291831#a69646070_481559
