### ISSUE TITLE
Devices list spinner is cropped and takes a long time [bz1308280]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#310]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1308280

Created attachment 8798538
ios-spinner-crop.png

STEPS TO REPRODUCE
With a few devices connected to Sync, go to send a tab and wait for the devices to appear

EXPECTED RESULTS
The list loads quickly but if necessary shows a spinnner

ACTUAL RESULTS
It shows a spinner that is cropped, and seems to take a long time to load devices

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1308280#a59281783_481559
