### ISSUE TITLE
Multiple Sync devices from the same iPhone showing up in desktop [bz1324438]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#312]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1324438

Created attachment 8819893
synced-tabs.png

STEPS TO REPRODUCE
Connect one iOS device and one desktop device to Sync
Have open tabs open on both
Send a tab from iOS to desktop
Open Synced Tabs on desktop

EXPECTED RESULTS
There is one iOS device

ACTUAL RESULTS
There are two

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1324438#a54603664_481559
