### ISSUE TITLE
Add "Retry" button to Sync sign-in failure page [bz1342376]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#314]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1342376

Created attachment 8840827
Simulator Screen Shot 23-Feb-2017, 3.38.02 PM.png

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0
Build ID: 20170125094131

Steps to reproduce:

When the internet connection is slow, the Sync sign-in page initially fails to load. I don't know what happens behind the scenes, but after showing the "Could not load page." text, when it succeeds loading the page, it does eventually display the sign-in screen without any further user navigation actions.

To simulate a slow internet connection and reproduce the scenario:
1. Turn Wifi/Mobile data off.
2. Go to Settings -> Sign In to Firefox

Actual results:

You'll notice that the wheel spins for a while before the page settles on the text "Could not load page." (in red). It's not possible to reproduce the automatic loading of the page behind the scenes which I described above.

Expected results:

A "Retry" button here would be nice (instead of having to go back to Settings and reattempting). See screenshot.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1342376#a54734504_481559
