### ISSUE TITLE
Sync client name isn't regenerated after restoring from backup [bz1343063]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#315]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1343063

I recently upgraded my iPhone, restoring from a back-up via USB, and noticed that my iPhone name has not assumed the latest device name.

STEPS TO REPRODUCE
1. Use Sync on Firefox for iOS
2. Take note of how the device name appears in Synced Tabs
3. Upgrade iOS device hardware, restore from back-up

EXPECTED RESULTS
- Device name is new device name (e.g. iPhone SE)

ACTUAL RESULTS
- Device name is old device name (e.g. iPhone 5S)

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1343063#a46827360_481559
