### ISSUE TITLE
Synced devices list can't be scrolled while the throbber is visible [bz1358467]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#319]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1358467

From https://bugzilla.mozilla.org/show_bug.cgi?id=1353377#c5

Richard Newman [:rnewman] 2017-04-09 20:21:54 PDT

I noticed this today when waking my iPad after it hadn't synced for a couple of days. The throbber is visible so long as the device is syncing, and while the throbber is visible you can't scroll the list. In my case that was about 45 seconds, which was kinda annoying.

I wouldn't mind having the throbber only 'link' to a sync if you pulled to refresh. Background syncs are a normal occurrence and shouldn't affect this kind of UI.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1358467#a40184452_481559
