### ISSUE TITLE
Synced Devices list disappears on phone lock [bz1371192]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#321]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1371192

Created attachment 8875611
Synced Devices after screen lock/unlock

1. Log into sync if you haven't already. Make sure you have other devices with open tabs logged into sync.
2. Go to History Panel -> Synced Devices
3. Wait for the synced tabs to appear.
4. Now, wait for the screen to blank out so that the phone gets locked.
5. Unlock the phone

You'll notice that the synced tabs list is no longer there. What you'll instead see is a message "There was a problem accessing tabs from your other devices. Try again in a few moments". See screenshot.

This problem doesn't happen if you manually lock the phone (by pressing the lock button) in step 4.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1371192#c3
