### ISSUE TITLE
Device list crashes the first time and won't send until sync is complete [bz1380551]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#327]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1380551

Created attachment 8886013
send-spinning.png

This is one to get right for our loyal users with large existing profiles.

STEPS TO REPRODUCE
1. Install Firefox for iOS Nightly fresh (I'm using iPhone SE)
2 On iOS sign into an existing account with a large profile (100 MB) and multiple devices
3. Before entire profile has synced, select Send Tab and select a device to send to

EXPECTED RESULTS
- Device names will with minimal delay
- User can send tab before all profile data has synced

ACTUAL RESULTS
- Device list crashes the first time Send Tab is selected
- The second time, before the Sync is complete, the device names loads, but the Send button is stuck on the spinner indefinitely (I’m assuming until the large profile is fully synced)

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1380551#a33044561_481559
