### ISSUE TITLE
Send tab to Device via force touch (Peek & Pop) is not working [bz1381012]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#330]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1381012

Build: 8.0 (4534) 
Device: iPhone 7
iOS: 10.3.2

Steps to reproduce:
1. Log in to FxA on desktop and iOS device
2. On iOS device, go to google.com
3. Tap the tab counter to open tabs tray
4. Force touch and swipe up on the google.com tab (Peek & Pop)
5. Tap 'Send to Device'
6. Select the device and hit send

Actual results:
- The tab is not sent do desktop. It can be observed that in the 'Settings' Firefox is 'Synchronising' and will remain in this state until closing and restarting Firefox. 

See video here:
- https://www.youtube.com/watch?v=Fe_3MXxkFFg

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1381012#a34903391_481559
