### ISSUE TITLE
In Settings replace Sign Out with Disconnect [bz1381112]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#331]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1381112

To reduce incidences of foot-gun violence, and be consistent with the other two platforms, we should rename Sign Out in Options to Disconnect.

Users believe that signing out will remove local data, and it does not.

Disconnect or Unlink is the conventional term for single-user clients with a synchronization feature.

**Comment by vladikoff** [comment]
This was fixed, https://github.com/mozilla-mobile/firefox-ios/pull/2962
