### ISSUE TITLE
Use Firefox Account server's /.well-known/fxa-client-configuration to configure servers in Firefox for iOS [bz1237407]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#332]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1237407

This is the iOS equivalent of Bug 1237406.  It's a little easier on iOS, I think, since we don't yet use any additional service endpoints (oauth, profiles, etc).

**Comment by vladikoff** [comment]
bugzilla will close this
