### ISSUE TITLE
Expose FxA account management via accounts.firefox.com [bz1246689]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#333]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1246689

Created attachment 8717028
account management (screenshot)

Currently the only opportunity to manage account management is on the off-chance that you happen to tap the account name in settings on account creation (verify email address) and an onClick is available [1] to be taken to account configuration URL.

[1] https://github.com/mozilla/firefox-ios/blob/b174304c4944b55a27cadf75ffc7ffda368db683/Client/Frontend/Settings/AppSettingsOptions.swift#L177

This is the only opportunity to manage an account. We should let the user manage an account on mobile.

Please dupe if this is part of a a different meta or under a 'v2' somewhere.

**Comment by vbudhram** [comment]
Mini feature doc for this https://docs.google.com/a/mozilla.com/document/d/1nktrt5BdPE1PLuXxtRL6FkK6MTR4zTSmydQWrBmaMeM/edit?usp=sharing
