### ISSUE TITLE
Display FxA avatar in settings [bz1382756]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#335]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1382756

If a user is signed in and has added an avatar, display that avatar in the settings panel. If no avatar is set, then display the placeholder avatar used in FxA website.

**Comment by vbudhram** [comment]
This is a thing now! Moving to blocked for bugzilla to close.
