### ISSUE TITLE
Open FxA verification links in Fx for iOS [bz1382776]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#337]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1382776

Currently, when you do sign in confirmation or email confirmation on iOS devices, the links open in Safari. If Firefox is installed we should be able to use universal linking to open them in the FxiOS.

**Comment by vbudhram** [comment]
All parts for this have merged and will be shipping in iOS 8.2.
