### ISSUE TITLE
If account unverified, tapping username should go to "Confirm your email" [bz1382777]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#338]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1382777

In unverified state, tapping username in settings should go to “Confirm your email” screen but just goes back.

**Comment by vbudhram** [comment]
Moving to block per https://github.com/mozilla-mobile/firefox-ios/pull/3135#issuecomment-332973992. This appears to have been fixed with content-server patch, https://github.com/mozilla/fxa-content-server/pull/5492. Moving to block until I verify it is fixed in prod.

**Comment by vladikoff** [comment]
Fixed https://bugzilla.mozilla.org/show_bug.cgi?id=1382777#c3
