### ISSUE TITLE
 Detect when account email has changed, and update local state on Android to match [bz1368147]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#340]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1368147

FxA is in the process of designing and prototyping the ability to change a user's primary email account. This bug is to help track any of the integration issues from this feature with respect to Firefox Android.

The current implementation goal is to move away (as much as possible) from using the email on the account table and start using email on the emails table. When a user `changes` their primary email, that email is set as the primary email in the emails table and will be used over the email on the account table. The email address on the account table needs to still exist because it is used to compute the password hash to login.

It was mentioned that Android FxA implementation uses an email that is assumed constant. It could be possible to update their session information with the new email, or even invalidate the session and require a login with new email?

What are some possible issues that could arise from this feature?

**Comment by vladikoff** [comment]
cc @rfk

**Comment by rfk** [comment]
@grigoryk is working on this but I can't assign it to him because he's not in any of our teams on github; invite sent

**Comment by grigoryk** [comment]
Patches up for review on bugzilla.

**Comment by rfk** [comment]
this landed \o/
