### ISSUE TITLE
Detect when account email has changed, and update local state to match in Desktop [bz1383663]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#341]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1383663

FxA will soon be shipping the ability for the user to change their primary email address.  Desktop Firefox may need to update its local login state when this happens, e.g. to ensure it displays the correct profile information to the.  This bug is for us to:

* Check for what information Firefox will need to update, if any
* Agree on how it will detect this change event
* Implement the necessary listeners etc to respond to the change.

Filing as a tracking bug for Q3 planning purposes.

**Comment by vladikoff** [comment]
@vbudhram @rfk could you triage this?

**Comment by vladikoff** [comment]
This is done
