### ISSUE TITLE
Logging out of Firefox for iOS does not tear down session/device state on server [bz1300641]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#343]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1300641

It appears that Firefox for iOS may not be destroying its session and/or device record when you log out of the device.  Steps to reproduce:

* Login to Firefox for iOS
* Visit https://accounts.firefox.com/settings?forceDeviceList=true
* Expand the "devices" view, and observe that the device is connected to your account
* Logout of Firefox for iOS
* Refresh the devices view.

Expected:

The device no longer appears in the list of devices connected to the account, because I've logged out of it.

Actual:

The device remains in the list.

My naive grepping through the source suggests that it's not calling either /session/destroy [1] or /account/device/destroy [2].  Please call one of these when logging out of the device, either /device/destroy if there's a device record active, or /session/destroy if not.

[1] https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#post-v1sessiondestroy
[2] https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#post-v1accountdevicedestroy

**Comment by shane-tomlinson** [comment]
@rfk, @vbudhram - can you triage this? It'll require some client work.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1300641#a73329399_481559
