### ISSUE TITLE
Disconnecting from Sync on Android does not remove device from FxA device list [bz1381828]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#344]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1381828

I signed into Sync using FxA then disconnected the device. When I looked at the device list in FxA, the device was still there.

STR:

1. On an Android device with Firefox for Android 54, sign into Sync using FxA.
2. On a desktop browser, sign into FxA using the email from step 1. Go to FxA's /settings page. Open "Devices & Apps". Ensure the newly connected device shows in the list.
3. In the Firefox for Android settings, click the name from step 1. Scroll down, click "Disconnect".
4. In the desktop browser, click the "Refresh" button. The device is still listed.

Expected: The device is not listed.

**Comment by shane-tomlinson** [comment]
@rfk, @vbudhram - can you triage this? It'll require some client work.

**Comment by vladikoff** [comment]
cc @eoger

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1381828#c5
