### ISSUE TITLE
Detect when account email has changed, and update local state on iOS to match [bz1384170]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#345]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1384170

Similar to https://bugzilla.mozilla.org/show_bug.cgi?id=1383663, with the coming ability of users to change their primary email address, we should be able to update the local state of the account in the app.

Currently, whenever a user changes their display name or avatar, a push notification is sent to notify corresponding clients up fetch the new data. In addition, if push fails or user declined it, FxiOS should be able to request updated profile data from the profile server and update the interface accordingly.

Stefan, is there any other references to a user's email that might also need to be updated, configs etc?

**Comment by vladikoff** [comment]
@vbudhram could you triage this out of the backlog if needed?

**Comment by vbudhram** [comment]
Pulling this into mobile quality backlog. I suspect that https://github.com/mozilla/fxa-bugzilla-mirror/issues/335 will also be related.
