### ISSUE TITLE
From deferred deeplink FxA Signin view could appear twice [bz1384179]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#346]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1384179

When launching FxA through a deferred deeplink there is a possibility that the FxA sign in screen will appear twice if a user goes all way through the onboarding flow and clicks `Sign In` at the end of it.

To prevent this, we could add a flag to check if this was app was launched from a deep link and when the user clicks `Sign In` from onboarding dismiss the view.

**Comment by vladikoff** [comment]
@vbudhram can you triage this?
