### ISSUE TITLE
Update basket when a user changes their primary email [bz1384385]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#347]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1384385

(Apologies if this is a dupe, I recall some discussion of this previously but couldn't find the bug)

FxA will soon ship and exciting new feature where the user can change the primary email address on their account.

We currently send every new account creation over to SMFC via basket, and manage opt-in to the Firefox newsletter via the user's Firefox Account.  What is the expected behavior inside basket/SFMC when a user changes their email with FxA?

I suspect it to be something along the lines of:

* If a user changes their email address, their record in the big list of all FxA users in SMFC, is updated to reflect the new email address
* If a user is subscribed to the Firefox Newsletter, and they change their email address, they remain subscribed to the newsletter under the new email address

But I'll need some help figuring out how that maps to the underlying data model, and how to make it so in practice.

Ben, :pmac, thoughts?

**Comment by shane-tomlinson** [comment]
@rfk - can you triage this?

**Comment by rfk** [comment]
Closing in favour of https://github.com/mozilla/fxa-auth-server/issues/2042
