### ISSUE TITLE
Sync: Your email was just returned [bz1385569]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#349]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1385569

Created attachment 8891638
Untitled.png

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
Build ID: 20170724055319

Steps to reproduce:

- Tried to sign in to Firefox sync
- Entered login info

Actual results:

I got the error message: "Your email was just returned"

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1385569#c15
