### ISSUE TITLE
Ensure that FxA change email does not break Pocket integration [bz1385869]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#350]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1385869

The main components for allowing a user to change their primary email in FxA has landed in our test environment and is available to @mozilla emails as an opt-in feature.

From original conversation with Pocket, they said that they use the FxA uid for tracking users and that there should minimal changes on their side to support it. 

This bug will be used to track any Pocket specific changes or updates needed for change email.

**Comment by vladikoff** [comment]
Pocket to verify this...

**Comment by vladikoff** [comment]
from mtg: Pocket to verify this later...

**Comment by davismtl** [comment]
from Sync fest:

Pocket will create a new account for the user if they change their primary email.

**Comment by vladikoff** [comment]
@rfk to comment on this...

**Comment by rfk** [comment]
The latest update from Pocket [1] is that this is taking a backseat to other work required for 57, but they still feel like they can ship it sometime in November.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1385869#c16

**Comment by vladikoff** [comment]
Tracking issue in Bugzilla...

**Comment by vladikoff** [comment]
from mtg: pocket is working on this in train-101

**Comment by vladikoff** [comment]
from mtg: pocket is working on this

**Comment by vladikoff** [comment]
from mtg: to be fixed early January

**Comment by vladikoff** [comment]
from mtg: check on Jan 16

**Comment by rfk** [comment]
done!

**Comment by davismtl** [comment]
@rfk any QA needed here?

**Comment by rfk** [comment]
We should verify this as part of QA-ing the rollout of the feature, but I don't think there are any *special* QA needs here.
