### ISSUE TITLE
@mozilla.com accounts always require email confirmation on login [bz1386042]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#352]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1386042

Logging in with a @mozilla.com address always requires an email confirmation (where you need to copy & paste a code).

This should probably be a narrower setting for specific RPs (or even specific pages like account config pages, etc), rather than for any RP.

Tested with the stable dev instance. Not 100% sure if prod is configured the same.

**Comment by shane-tomlinson** [comment]
@mozilla.com addresses do not require confirmation, but they do require an unblock code.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1386042#c3
