### ISSUE TITLE
Closing the pre-filled log in form and opening a new one will display empty address [bz1386636]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#353]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1386636

Device: Samsung Galaxy S6 EDGE 
OS: Android 7.0

STR:

On desktop
1. Create new FxA on desktop client
2. Send SMS install link to Mobile user
On mobile: 
3. Close the address prefilled login form
4. Go to settings-Sign in

Expected: Email address prefilled
Actual : Empty address field

For further details please check: https://www.youtube.com/watch?v=aRVjUd9cAGs&feature=youtu.be

**Comment by ryanfeeley** [comment]
@philbooth I agree with the expected behaviour. What would be required to make it happen? Client or web?

**Comment by shane-tomlinson** [comment]
> @philbooth I agree with the expected behaviour. What would be required to make it happen? Client or web?

Most likely, both.

**Comment by shane-tomlinson** [comment]
> @philbooth I agree with the expected behaviour. What would be required to make it happen? Client or web?

On second thought, we *might* be able to get away with doing a web-only thing as long as localStorage acts sanely on Firefox for Android.
