### ISSUE TITLE
Deferred deep linking does not work if you wait longer than 3s to start browsing [bz1388408]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#354]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1388408

After working Adjust support, we were able to find out why we had inconsistent experiences with deferred deep linking. When a new user is shown the onboarding flow they about 3 seconds to click `Start Browsing` before the deferred deep link does not work.

To help resolve this, we can add a user preference to be set when the user has launched the application from a deferred deep link. Then capture the link and launch the FxA sign-in page appropriately.

**Comment by vladikoff** [comment]
from mtg: waiting for it to be merged
