### ISSUE TITLE
When Disconnecting Firefox Account, buffer bookmarks are removed from device [bz1392758]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#359]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1392758

While testing bi-directional bookmarks, we realized that when you disconnect your account, we delete all your local bookmarks from your device. Only your bookmarks and nothing else.

If our intention is to delete data after a disconnect, we need to delete EVERYTHING. Not just bookmarks.

If our decision is to leave everything on the device then we need to make sure we don't delete all the bookmarks.

This bug touches a topic related to some other bugs like
Bug 1162778
Bug 1325271

I believe the proposal from Bug 1162778 is the correct way to go. We should ask users what desired behavior they would like.

I don't want to flag these as duplicate yet because the behavior of bookmarks here needs to be documented and addressed.

**Comment by shane-tomlinson** [comment]
@rfk - This seems like an iOS bug rather than an FxA bug, can you traige this appropriately?

**Comment by rfk** [comment]
Agreed, this doesn't need to be tracked in the FxA waffleboard.
