### ISSUE TITLE
Sync Account blocked due to confirmation email returning [bz1393471]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#362]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1393471

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Build ID: 20170822171841

Steps to reproduce:

User tries to log-in to Sync and is asked to verify e-mail.

Actual results:

User gets the message: "The confirmation email we sent to %(email)s was returned and we’ve locked your account to protect your Firefox data."

Expected results:

User should have access to his account.

**Comment by shane-tomlinson** [comment]
User can now sign in, closing.
