### ISSUE TITLE
Camera and Photo Library fail to open when trying to add an account picture [bz1393746]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#365]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1393746

master 9baa97bb2
iPhone 6 Plus, iPhone 7 (10.3.3)

1. Sign into FxA.
2. Tap on the email address to open the account management page.
3. Tap on Add account picture.
4. Tap on Upload.
5. Tap on Camera or Photo Library.

Expected: Camera/Photo Library app should open
 
Actual: The account management page is dismissed

From what I noticed, this issue happens only on iPhones, not on iPads

Client[7546:1286370] Warning: Attempt to present <UIImagePickerController: 0x105145000> on <Client.SettingsNavigationController: 0x1050a0a00> whose view is not in the window hierarchy!

**Comment by shane-tomlinson** [comment]
Fixed by https://github.com/mozilla/fxa-content-server/pull/5480, closing.
