### ISSUE TITLE
Send a transactional email to all registered Firefox Accounts users on September 19 [bz1393842]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#366]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1393842

Legal needs to send a transactional email to all registered Firefox Accounts users on September 19. Draft copy is located here: https://docs.google.com/document/d/1pFSCzwReHkQCm9H_XcADLOMo6KN-3mu9eQDMed6dmQI/edit

With the release of Firefox 56 on September 26, we are going to be updating the Cloud Services TOS and rolling the Cloud Services PN into the browser PN. This means we need to let users know that these changes are coming ahead of time. We would like to send notice one week in advance, thus we need to do this on Sept. 19.

**Comment by shane-tomlinson** [comment]
@rfk - I'm putting this in active with your face, because well, you are doing all the coordination. Can you triage as appropriate?

**Comment by rfk** [comment]
Thanks :-)

Latest resolution is that we're going to try to do it in salesforce, with no engineering work required on our side.  I'll keep a close eye on it and update status here as appropriate.

**Comment by vladikoff** [comment]
Marketing is doing this .

@rfk to change bugzilla fields
