### ISSUE TITLE
Please provision production oauth credentials for "Paths" project [bz1395037]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#367]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1395037

Project Paths is a new relier currently in development, and using credentials in our dev environment.  Can we please provision some production credentials to be ready for when they launch?  The details are:

  Client ID:     bfe4b2f7da6ac439
  Name:          Firefox Paths
  Redirect URI:  https://mozill-paths.starty.io/auth/firefox
  Trusted:       true

The name and redirect_uri will probably need to be updated once they're ready to go live, but if we can provision it for QA in the meantime that'll be useful.

I will get the lead dev hooked up on this ticket to coordinate secure handoff of client secret.

**Comment by juliemccracken** [comment]
Re. questions about whose project "Paths" is...Paths is being done by an external company...don't know their name. Nick Chapman is working with them on our side.

**Comment by rfk** [comment]
> Paths is being done by an external company...don't know their name

External dev lead is https://andyet.com/team/gar/

**Comment by vladikoff** [comment]
Waiting for gpg keys

**Comment by vladikoff** [comment]
cc @nchapman

**Comment by vladikoff** [comment]
cc @davismtl @nchapman
