### ISSUE TITLE
Confirm your account pref screen should no longer redirect to Sync prefs [bz1357085]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#372]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1357085

Created attachment 8858805
1080p.mov

Now that the Firefox Accounts team is providing a "Connect Another Device" experience on the web, instead of redirecting just-verified users to Sync prefs, we should instead give the web control.

Current experience shown.

**Comment by shane-tomlinson** [comment]
Blocked on @kitcambridge's browser patch and our code going to prod.

**Comment by vladikoff** [comment]
Waiting for train-96...  :+1:

**Comment by vladikoff** [comment]
Firefox patch ready to land...

**Comment by rfk** [comment]
Fixed in bugzilla
