### ISSUE TITLE
Sync icon stops spinning after backgrounding/foregrounding the app [bz1398822]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#375]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1398822

master ffdce75bae212

1. Go to Settings and sign in to sync
2. Initiate a sync
3. While sync is in progress,background then foreground back the app.

Result: Sync icon stops spinning although the sync is still in progress.

**Comment by vladikoff** [comment]
from mtg: @vbudhram got a PR for that!
