### ISSUE TITLE
Cleanup observers in settings screen [bz1403000]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#377]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1403000

From https://bugzilla.mozilla.org/show_bug.cgi?id=1400883#c5, we should cleanup observers when settings page is not visible.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1403000#a39306435_481559
