### ISSUE TITLE
"Last sync" dates are inaccurate in sync preferences [bz1403275]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#378]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1403275

Created attachment 8912352
Screenshot

I don't have an STR but my tabs are up to date on my remote devices and the "Last sync" date is at least 2 months old: see the attached screenshot.

Running macOS Sierra on a Nightly only a few days old.

**Comment by vladikoff** [comment]
Fixed via https://github.com/mozilla/fxa-auth-server/pull/2149
