### ISSUE TITLE
Send country to basket + salesforce [bz1405310]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#380]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1405310

Problem:We do not have country field data populated for Firefox email opt-ins from Firefox Accounts.

Can you add this parameter to the Basket calls that add someone to Salesforce CRM when they've opted in?

We do not currently store this field in the root Firefox Accounts Data Extension in Salesforce Marketing Cloud (SFMC): "Firefox_Account_ID" [1]

Let us know if that is a prereq to be able to pass it through for opt-in email subscribers.

Not urgent - but super helpful to have sooner rather than later.

Thanks!

Jess

[1] Shared Items > Shared Data Extensions > Firefox & You Lists > Firefox Accounts > Firefox_Account_ID

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1405310#c13
