### ISSUE TITLE
confirmation email @tonymharris.com was returned and account locked [bz1406943]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#384]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1406943

User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0
Build ID: 20170926190823

Steps to reproduce:

Tried to login to my Firefox Sync account but was locked out. This is a forwarded email

Actual results:

Error message: Sorry. We’ve locked your account. The confirmation email we sent to photo@tonymharris.com was returned and we’ve locked your account to protect your Firefox data.

Expected results:

A confirmation email should of been seen to my email account

**Comment by philbooth** [comment]
ping @jbuck
