### ISSUE TITLE
context used to load Firefox Accounts on https://www.mozilla.org/firefox/accounts/ should be `fx_firstrun_v2` instead of `iframe` [bz1407579]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#385]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1407579

The context used to load FxA on https://www.mozilla.org/firefox/accounts/ is `iframe` whereas the firstrun page moved to `fx_firstrun_v2` in Firefox 46 (I believe). The correct context for mozill.org/firefox/accounts is `fx_firstrun_v2` also. 

The primary difference between `iframe` and `fx_firstrun_v2` is that the latter shows the "Choose What To Sync" screen to users who sign up for a new account. In addition, there are some extra events [1] sent to the containing page that can be used for performance tracking.

[1] - https://github.com/mozilla/fxa-content-server/blob/594caa03d2ab4c2dc2db6a37d00b3c9c2bb30de6/app/scripts/models/auth_brokers/fx-firstrun-v2.js#L37

**Comment by shane-tomlinson** [comment]
Putting this in blocked because the moz.org webdev team needs to handle this.

**Comment by shane-tomlinson** [comment]
I closed the bugzilla bug as invalid, `context=iframe` is only used on Fx <= 45. The page uses fx_firstrun_v2 for fx >= 46.
