### ISSUE TITLE
Back button during sync setup/ should return to previous Activity [bz1217164]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#386]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1217164

STR:
0) With no account activated
1) Settings -> Sync (sync setup tab opens)
2) Hit back

Expected: User returns to Sync Settings (or browser tab that occurred before Settings)
Actual: Browser closes

In particular, once I finish signing into an account, my temptation is to hit back to return to the previous tab I was working with because there's no button to dismiss sync setup then I get booted from the browser. As such, I've marked this for onboarding because it's an unintuitive experience.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1217164#a91306025_481559
