### ISSUE TITLE
“Sync Now” doesn’t look like a button [bz1325024]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#387]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1325024

Created attachment 8820627
螢幕快照 2016-12-21 17.55.29.png

When sync enabled, "sync now" is not look like a button, and also propose to provide more details for sync contents, such as bookmarks, history, etc.

The left figure in the attachment is the current design;the right figure in the attachment is the desirable design.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1325024#a52744633_481559
