### ISSUE TITLE
Sync preference button has different height [bz1398282]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#389]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1398282

Under Settings, notice that the height of the first item - sync preference button with user's email and avatar - isn't as tall as the rest of the menu. It's inconsistent, and margins around the avatar are very tight visually.

**Comment by vbudhram** [comment]
This has been fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1407743
