### ISSUE TITLE
Indicate more Sync/FxA error states [bz1398293]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#391]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1398293

It's possible for us to fail to obtain GCM tokens, for a variety of reasons. It's also possible to fail to register with Autopush in some other way, or to have our Autopush registration in a broken state.

It would be good to indicate to the user that something isn't functioning correctly. It's not always a user-recoverable issue, but sometimes it is. We now use push to make Send Tab speedier, and reporting push error states will help ensure less confusion, give users ability to try basic recovery, and will make for easier debugging.

Ideally we can be both specific in what our error state is ("no permission X", "server error", etc), and perhaps provide basic instructions on how to recover ("did you try turning it off and on again?").

I'm thinking that Sync prefs is a good place to put this. Perhaps a discardable system notification as well, showed the moment we discover we're in a broken state?

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1398293#a36727975_481559
