### ISSUE TITLE
[sync-send tab] Frozen spinner is shown when there are no devices to send tab to (iOS) [bz1385458]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#399]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1385458

steps to reproduce:
1. Login to your sync in iOS device
2. open any http or https page and press "send tab"

Actual Result
Frozen spinner is shown when there are no devices to send tab to (iOS)

Expected result:
Sync should not spin indefinitely if it does not get a device.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1385458#a40345257_481559
