### ISSUE TITLE
fxa oauth key for addons.thunderbird.net [bz1411385]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#400]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1411385

I'm setting up a clone of https://github.com/mozilla/addons-server running on Mozilla AWS, and it'll need an fxa oauth key. The purpose of this is to serve Thunderbird/Seamonkey addons because the new addons.mozilla.org front-end that is launching soon doesn't support those applications.

Not sure if any other information is required, let me know if there is.

Thanks!

**Comment by shane-tomlinson** [comment]
@rfk - I'm putting this in active - can you re-triage and pass on as appropriate?

**Comment by vladikoff** [comment]
> Also worth nothing, this site is intended to go live by Nov 10, so we'll need to have the credentials ready before then

cc @jbuck
