### ISSUE TITLE
confirmation email returned and account locked (firefox sync) [bz1411407]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#401]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1411407

Email address (firefox@soelzama.com) is confirmed working (was able to create a new bugzilla account using the same address to file this report). The issue is that the domain's MX record was updated not long before the confirmation email was sent resulting in a bounce back. 

Can the account simply be unlocked so that a request can be made to have the confirmation email sent again?

**Comment by vladikoff** [comment]
Resolved
