### ISSUE TITLE
Confirm your account screen is behind webview header [bz1411297]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#403]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1411297

Created attachment 8921510
hidden.png

Somehow the FxA web view is reverse scrolled, hiding the logo, on the Confirm your account page. Not sure what's happening here, but the user cannot even scroll down if they want to.

Am on iPhone SE.

**Comment by vladikoff** [comment]
Fixed!
