### ISSUE TITLE
Re-enable FxA Leanplum A/B push test [bz1414010]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#407]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1414010

FxA recently landed code to perform A/B testing for push permissions. However, this feature had to be disabled before app was published to App Store because of conflicting configurations. Spoke with st3fan and we mapped out what the correct configuration is needed for this to be enabled in production.

  * Expose a `isEnabled()` function that looks into the SDK and checks that Leanplum is enabled for a given loaded local, else don't perform A/B test. We can not rely on the SDK feature flag to say that user would/wouldn't get test.
  * Add a Leanplum remote configuration variable that can turn off this feature. Only users with this configuration set to true will be enrolled in A/B test.

Once this had been added, we should be able to safely sync the new message templates and variables and turn on the experiment for users.

**Comment by vladikoff** [comment]
101!

**Comment by vladikoff** [comment]
from mtg: still in review

**Comment by vladikoff** [comment]
from mtg: still in review
