### ISSUE TITLE
"Unexpected error" when creating an account [bz1415768]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#408]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1415768

Original from https://webcompat.com/issues/13233

== User report summary ==

I just logged-in and it was showing error while I have 4Mbps internet speed.
And trying 7-8 times it started showing same error on next page.

https://webcompat.com/uploads/2017/11/3db78088-bdc1-4c45-8fb3-09b35f1cf223.jpeg

== User report summary ends ==

**Comment by shane-tomlinson** [comment]
Backlogging until we have more reports of this, we are looking at the server logs to see if we can find any useful info.

**Comment by vladikoff** [comment]
Could be caused by a spotty connection and somehow a 500 got into the email polling..

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1415768#a5272875_481559
