### ISSUE TITLE
2 step verification on firefox account [bz1417078]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#410]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1417078

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Build ID: 20171112125346

Steps to reproduce:

I logged in to firefox account for use sync & rate the add-ons but found that firefox account don't have 2 step verification settings for me to improve security for my account.

Actual results:

I don't have 2 step verification or multi-factor authentication on firefox account. There are no settings about this.

Expected results:

Firefox should have it to improve user's security like the other did such as Google account.

**Comment by rfk** [comment]
I'm not sure "active" is the right classification for this; IIUC the user is asking more for Google-Authenticator-style "proper" 2FA which is not currently in scope for Q4.  @vbudhram thoughts?

**Comment by vbudhram** [comment]
@rfk Yea, re-read the bug they did mention a more Google based method. That considered, this is probably a backlog or can close.
