### ISSUE TITLE
Erroneous emails, Subject "[Final ]Reminder: Complete your Firefox Sync Setup" [bz1419119]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#417]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1419119

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0
Build ID: 20171112125346

Steps to reproduce:

Created Firefox sync account on MacOs laptop and iphone, both on 11/15/17.

Actual results:

I received two emails, on 11/16 and 11/20, which say "Uh oh. You’re not syncing to another Firefox yet."  But on my iPhone Firefox app, under Settings/Firefox Accounts/Devices & Apps, it clearly displays both accounts, which are correctly syncing.  (I don't see how to get the same information from the MacOS version of Firefox.)

Expected results:

I should not have received the emails.

PS I love what you've been doing!  Great work.

**Comment by rfk** [comment]
Declining to track this in waffle
