### ISSUE TITLE
Improve the messaging to the user after they changed password [bz1419552] 

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#419]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1419552

STEPS TO REPRODUCE
- Register for Sync from Firefox desktop
- Sign in from an iOS device
- Return to desktop and change the account password
- View synced tabs on iOS

EXPECTED RESULTS
- Synced tabs are shown

ACTUAL RESULTS
- User is disconnected and taken to a force auth screen
- Desktop still may show as connected in synced tabs
- Can still appear to send tabs (but they never arrive)
- Changed password eventually makes its way over

**Comment by vladikoff** [comment]
> from mtg: we will improve the messaging to the user after they changed password

**Comment by vladikoff** [comment]
for q1

**Comment by vladikoff** [comment]
close in favour of https://github.com/mozilla/fxa-bugzilla-mirror/issues/431
