### ISSUE TITLE
Desktop not receiving "fxaccounts:device_disconnected" push notifications [bz1423015]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#420]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1423015

I've been able to reproduce this 100% of the time in around 10 attempts over the last day. Thom has reproduce it once. Ed has offered to try and repro tomorrow.

STR:
* Have 2 desktop devices connected to the same FxA account and running.
* On one device use FxA to disconnect the other.

Expected:
* The disconnected device gets a push notification that completely disconnects sync.

Actual:
* The disconnected device continues to sync until the token server token expires, then enters a regular "please reconnect" state (ie, the state described in bug 1422679)

IOW:
* Bug 1422679 is the fact that desktop doesn't quite do the right thing if a push fails to arrive.
* This bug is about the push failing to arrive.

**Comment by vladikoff** [comment]
waiting for train deploy to check this
