### ISSUE TITLE
Expose FxA login state when not accessing from FxAContentViewController [bz1425351]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#423]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1425351

To help support https://github.com/mozilla/fxa-content-server/issues/5743 we need the ability for FxiOS to expose the FxA login state to the FxA web content. This will allow us to give the correct messaging to users when they verify from within FxiOS.

An initial implementation could include rendering a hidden div with the following properties.

```
<div id="fxa-state" data-state="verified" data-devices="1"/>
<div id="fxa-state" data-state="unverified" data-devices="1"/>
<div id="fxa-state" data-state="not-logged-in" data-devices="0"/>
```

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1425351#c5
