### ISSUE TITLE
FxA and sync servers get a "B" on SSLlabs tests [bz1219547]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#424]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1219547

The core servers for the FxA connected experience all get a "B" rating from SSLLabs, e.g:

  https://www.ssllabs.com/ssltest/analyze.html?d=accounts.firefox.com
  https://www.ssllabs.com/ssltest/analyze.html?d=token.services.mozilla.com

The reason it gives is that:

  "This server supports weak Diffie-Hellman (DH) key exchange parameters.
   Grade capped to B."

Sadly I don't think we can do anything about that yet, but I wanted a bug on file to track it (and to point at when this topic comes up again).

The reasoning behind the current situation is that we have certain clients (e.g. old android devices, partner devices like Bug 1186900) that do not support the "modern" TLS configuration recommended in [1].  Instead we must use the "intermediate" configuration [2] which includes DH ciphers.

These ciphers are fine *if* you use secure DH parameters.  But the TLS support for FxA and Sync is provided by Amazon's Elastic Load Balancers, which don't let you customize the DH parameters.

So I think we're stuck on a "B" grade until all our clients grow more modern TLS support, or Amazon gives us better tools to customize TLS on the ELBs.

[1] https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility
[2] https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1219547#a67518962_481559
