### ISSUE TITLE
Require minimum complexity on Firefox Account password [bz1425860]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#425]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1425860

FxA should require its users to set a reasonably strong password to protect their account. What is considered "reasonably strong" is up for debate, but we could start with the following rules:

- cannot match the username
- cannot be a dictionary word (need to support several languages)
- cannot be shorter than 8 characters
- from 8 to 12 characters, should contain at least two classes of characters (uppercase,  lowercase, numbers, special chars)
- above 12 characters, can contain a single class of characters

New accounts should match this policy, and I would propose that we inform existing accounts that their password is weak upon login, and invite them to change it.

**Comment by vladikoff** [comment]
subset users will get this in 116

**Comment by shane-tomlinson** [comment]
This experiment is now released to 10% of users, see:

* https://analytics.amplitude.com/mozilla-corp/chart/4b90aw2
* https://analytics.amplitude.com/mozilla-corp/chart/jvwikep

**Comment by vladikoff** [comment]
blocked: waiting for experiment to complete

**Comment by vladikoff** [comment]
from mtg: enable this for RTL locales 50 / 50, @rfk to file a bug

**Comment by rfk** [comment]
> @rfk to file a bug

https://github.com/mozilla/fxa-content-server/issues/6516

**Comment by shane-tomlinson** [comment]
Closing as fixed.
