### ISSUE TITLE
[SUMO User Issue] Verification email not received after 48 hours [bz1426192]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#426]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1426192

Via: 
https://support.mozilla.org/en-US/questions/1194952?page=2

Troubleshooting already done: 
1) Antivirus stopped
2) Checked spam
3) not blocking accounts@ email
4) error message that the email is not an email. 
5) waited 24 hours to try to sign up again
6) asked user to update to 57 (however the older version should still work with the sync system)
 
Expected - to receive an verification email
What happened - none recieved. 

Domain of the email address jon@hagleskyting.no

Thank you for taking a look at this.

**Comment by vladikoff** [comment]
Closed in bugzilla
