### ISSUE TITLE
firefox account secondary email can't use same address as another firefox account [bz1427796]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#430]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1427796

User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Build ID: 20171206182557

Steps to reproduce:

Create a Firefox account with email address (A).
Create a Firefox account with email address (B).

Log into (B). Try to add same email address as (A) as a "secondary email" for (B).

Actual results:

"Account already exists."

Expected results:

Secondary email address should be any arbitrary email address, irrespective of  any other Firefox account existing that utilizes it. Secondary email address SHOULD, of course, be verified after the request, but it shouldn't be restricted from being the same as another account -- especially since the "red route" for many users and uses is to have multiple Firefox accounts.

**Comment by vladikoff** [comment]
This is by design.
