### ISSUE TITLE
[SUMO User Issue]  Specific email not receiving emails Investigation of <riskala@labema.fi> [bz1434987]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#453]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1434987

User: 
Support Case link

The user has no access to removed email account specified

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1434987#c2
