### ISSUE TITLE
Enable FxA Leanplum A/B push test for release [bz1435135]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#454]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1435135

FxA A/B testing for push priming has landed and tested for Beta users. We should now be able to open it up for all users.

Ref: https://www.leanplum.com/dashboard#/5432682399399936/report/overview/6266604381536256

**Comment by vladikoff** [comment]
Waiting for ios 10.7 release.  https://bugzilla.mozilla.org/show_bug.cgi?id=1435135#a311355_481559
