### ISSUE TITLE
Misaligned button in the account management page [bz1434200]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#456]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1434200

Created attachment 8946580
Refresh button.mov

iPhone 8 Plus (11.2)
Firefox 11.0 Beta 8821

1. Sign into Fxa.
2. Go to Firefox Settings and tap on the email address.
3. Tap on Manage Account. 
4. In the account management page tap on "Show" Devices & Apps.
5. Tap on "Refresh".  

Result: The "Refresh" button gets misaligned when tapped.

**Comment by vladikoff** [comment]
cc @vbudhram

**Comment by vbudhram** [comment]
For reference, I was able to replicate this with the following minimum `clients.mustache` file
```html
<div id="clients" class="settings-unit {{#isPanelOpen}}open{{/isPanelOpen}}">
  <div class="settings-unit-stub">
    <header class="settings-unit-summary">
      <h2 class="settings-unit-title">{{#t}}Devices & apps{{/t}}</h2>
    </header>
    <button class="settings-button secondary settings-unit-loading" disabled>
      <div class="spinner spinner-settings-fetch"></div>
    </button>
    <button class="settings-button secondary settings-unit-toggle" data-href="settings/clients">
      {{#t}}Show{{/t}}
    </button>
  </div>

  <div class="settings-unit-details">
    <div class="error"></div>

    <form novalidate class="client-list-form">
      <div class="button-row">
        <button type="submit" class="settings-button primary clients-refresh"></button>
        <button class="settings-button secondary cancel">{{#t}}Done{{/t}}</button>
      </div>
    </form>
  </div>
</div>
```

When there is next in the button, it aligns properly. When the spinner is added or if no text, the button become misaligned. Will continue to investigate since there appears to be no trivial solution.
