### ISSUE TITLE
Can't unlock account - sign in help [bz1436629]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#459]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1436629

Created attachment 8949265
index.png

User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Build ID: 20180128191252

Steps to reproduce:

Try to sign into sync 

Actual results:

Was told (Sorry. We’ve locked your account.)

Expected results:

I need sign into sync my account because of business accounts. You sent me an email already saying this is not a bug and contact mozilla. I did and they told me to contact you for you to fix. This is not a game, i'm losing money because i cant access accounts. Someone please do something, i mean im contacting from the email address it's blocking, don't you think that's weird. COME ON WAKE UP AND UNLOCK MY ACCOUNT

**Comment by vladikoff** [comment]
Will be fixed when pr for mozilla/fxa-content-server#5776 lands
