### ISSUE TITLE
"Add Account picture" option is missing in FxA account management page on iOS 10.x [bz1437042]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#460]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1437042

Created attachment 8949739
Screen Shot 2018-02-09 at 16.20.43.png

Build: 11.0(9002)
iOS: 10.3.2
Device: iPhone 6

Steps to reproduce:
1. Log in to FxA
2. Go to Firefox settings => tap on the email address => tap on "Manage Account" 

Actual results:
- Unable to add account picture because the option is missing on iOS 10.x

**Comment by vladikoff** [comment]
@vbudhram to close this
