### ISSUE TITLE
Firefox Logo is black when opening a url of "Confirm sign" button in "Confirm new sign-in to Firefox" email using Microsoft Edge [bz1439201]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#470]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1439201

Created attachment 8951961
confirm-new-sign-in-to-firefox-in-microsoft-edge.png

Steps to reproduce:
1. Receive "Confirm new sign-in to Firefox" email
2. Open "Confirm sign" button's url using Microsoft Edge

Actual results:
Firefox Logo is black.

Expected results:
Firefox Logo is fine.

**Comment by hritvi** [comment]
Hii @rfk. I would like to work on this issue. Any advice on where and how to get started with the implementation will be helpful. :)

**Comment by vladikoff** [comment]
@hritvi Hello, check if logo is black in Edge, if so then you might want to check if it has something to do with the PNG we are using

**Comment by hritvi** [comment]
![Screenshot (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a987268f5313500112e470f/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0cb9d665043761260ea62864c7b96aea1722075b5e1fad125a5f4cf9fb8b22a6b639708d0d5aeac3714d36976345f3e5db55ea43a82a994e82bcbd8f4ec0e93e2de18d8a4f38161755.png)
Yes the image is coming black in edge. But in the debugger tools the image has been received with status code "200" and also in the url the image is proper. 
The url of logo : https://accounts-static.cdn.mozilla.net/images/6c1e077e.firefox-logo.svg

**Comment by vladikoff** [comment]
@hritvi if you navigate directly to the logo is it still black?  Check the one on https://design.firefox.com/photon/visuals/product-identity-assets.html if that one is fine we need to replace it with the one that works

**Comment by hritvi** [comment]
On directly navigating to the photo it is proper.

**Comment by hritvi** [comment]
Can u please help me in setting this up on my localhost. Thanks :)

**Comment by vladikoff** [comment]
@hritvi see https://github.com/mozilla/fxa-content-server/blob/master/README.md#quick-start

**Comment by hritvi** [comment]
Hii @vladikoff . Thanks for the link. I am done with setting it up on my localhost. Regarding this issue, it seems to be very common issue faced in microsoft edge and IE. These are two more issues regarding the same https://github.com/kisenka/svg-sprite-loader/issues/163 https://github.com/iconic/SVGInjector/issues/23
Looking more into this now.

**Comment by hritvi** [comment]
Hey @vladikoff 
For some reason IE and edge doesn't evaluate style tags included in dynamically added/inlined SVG files. 
I have found a fix for this
```javascript
var styleTags = svg.querySelectorAll('style');
      forEach.call(styleTags, function (styleTag) {
        styleTag.textContent += '';
      });
```
This need to be embedded in a file which is automatically called during the injection process for each SVG. I am unable to figure out that file. Kindly help me to locate that file so that I can add this fix. Thanks :)

**Comment by hritvi** [comment]
@vladikoff any updates on this bug. Thanks!

**Comment by hritvi** [comment]
I am looking for a js file which is called at runtime when this svg file is injected so that I can embed this fix in that file. Thanks!

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1439201#c1
