### ISSUE TITLE
accounts@firefox.com sends with antique encryption (a59-51.smtp-out.us-west-2.amazonses.com [54.240.59.51]) [bz1442994]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#472]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1442994

> From: Firefox Accounts <accounts@firefox.com>
> Subject: Neue Anmeldung bei Firefox =?UTF-8?Q?best=C3=A4tigen?=
(confirm new login)

> Received: from a59-51.smtp-out.us-west-2.amazonses.com (a59-51.smtp-out.us-west-2.amazonses.com [54.240.59.51])
>	(using TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits))
>	(Client did not present a certificate)
>	by mx.h.terrax.net (Postfix) with ESMTPS id 3zvQBz3G7RzBhJx

* missing TLSv1.2 (e.g. with ECDHE-RSA-AES256-GCM-SHA384)
* missing client certificate (see also: bug 1439915)
* missing IPv6
* DKIM is rsa-sha256 (yay!)

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/security.html
> Amazon SES to Receiver
> 
> Amazon SES sends messages over a TLS-protected connection (TLS version 1.0 only) by default.

So by default one should not use Amazon SES to send mail. :/

**Comment by jrgm** [comment]
Pending upstream change from SES

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1442994#a700872_481559
