### ISSUE TITLE
Confirmation email from Sync never arrives to gmail [bz1443515]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#474]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1443515

Created attachment 8956455
bug Firefox Sync Capture d'écran 2018-03-06 15.58.39.png

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Build ID: 20180206200532

Actual results:

Confirmation email from Sync never arrives to churkeshea@gmail.com
Sorry for my English:
Impossible to have acces in Sync, not acces bookmarks
Thank you

**Comment by shane-tomlinson** [comment]
Closing as FIXED
