### ISSUE TITLE
Login to AMO failed because of these errors [bz1443701]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#475]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1443701

User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0
Build ID: 20100101

Steps to reproduce:

Try to login to AMO.
1. On AMO webpage, click signin/login link.

Actual results:

TypeError: setting getter-only property "navigationStart"
[Learn More]
navigation-timing.js:39
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://accounts.firefox.com https://accounts-static.cdn.mozilla.net”). Source: onclick attribute on A element.
signin

TypeError: this._speedTrap.init is not a function
Stack trace:
o@https://accounts-static.cdn.mozilla.net/bundle-089f09d69396fa4f85d04b4929460c2a33552eba/app.bundle.en.js:1:75001
_createMetrics@https://accounts-static.cdn.mozilla.net/bundle-089f09d69396fa4f85d04b4929460c2a33552eba/app.bundle.en.js:1:207529
initializeMetrics@https://accounts-static.cdn.mozilla.net/bundle-089f09d69396fa4f85d04b4929460c2a33552eba/app.bundle.en.js:1:198030
initializeDeps/<@https://accounts-static.cdn.mozilla.net/bundle-089f09d69396fa4f85d04b4929460c2a33552eba/app.bundle.en.js:1:196693

Expected results:

I was able to login last week. It's clear this is your side's problem.

**Comment by vladikoff** [comment]
This release: https://github.com/mozilla/fxa-content-server/releases/tag/v1.106.7 should fix that

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1443701#c10
