### ISSUE TITLE
Link to Download iOS Version Does Not Take Effect After Desktop Login Synchronization [bz1444792]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#477]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1444792

Created attachment 8958022
connecting to apple music

Version 	58.0.2
Version ID 	20180206200532

After the desktop login is synchronized, it will prompt to download iOS and Android version. 

https://accounts.firefox.com/connect_another_device?service=sync&context=fx_desktop_v3&entrypoint=menupanel

Click 'download on the App Store' button and sometimes it links to blank page, or show 'Connecting to Apple Music...'.

Rarely it is possible to display the correct App Store preview page, but the country and region of the App store don't match the language used by my firefox. For example, my firefox and page language are both simplified Chinese, but the App Store shows countries and regions are the United States.

**Comment by vladikoff** [comment]
Need to check Safari...

**Comment by vladikoff** [comment]
Even Safari on desktop does the right thing for me...

ref https://bugzilla.mozilla.org/show_bug.cgi?id=1444792#c3
