### ISSUE TITLE
Confirmation email from Sync never arrives to address ***@free.fr [bz1446746]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#479]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1446746

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
Build ID: 20180315233128

Steps to reproduce:

Can't connect to my sync account. 

Actual results:

My email account was blocked by my provider and is now activated.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1446746#c2
