### ISSUE TITLE
Unable to sign in to sync [bz1447441]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#480]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1447441

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Build ID: 20180319175655

Steps to reproduce:

I tried to login to Firefox to sync with my existing account.

Actual results:

I received the following error: "Unable to deliver email". Here is a screenshot: https://i.imgur.com/m6WCAn1.png.

Expected results:

I should have been able to login to my account. I have done this several times before on many different computers. This is the first time this has happened.

**Comment by vladikoff** [comment]
That's a new one O_o

**Comment by vladikoff** [comment]
Error: https://github.com/mozilla/fxa-content-server/blob/340cb54091b38aa94b6fe73162fea037face1961/app/scripts/lib/auth-errors.js#L146

can we enhance the messaging?

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1447441#c1

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1447441#a21095955_481559
