### ISSUE TITLE
Account is locked because email verification was returned despite having successfully verified email account. [bz1447477]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#481]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1447477

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0
Build ID: 20180315233128

Steps to reproduce:

-Created a new Firefox account.
-Successfully verified email.
-Logged in on a browser on computer #1.
-Tried to log in on a browser on computer #2.

Actual results:

Was unsuccessful when trying to log in on second computer. Received a message saying the account was locked because the email verification wasn't received.

Expected results:

Should be able to add my account to more devices.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1447477#a16850144_481559
