### ISSUE TITLE
SMS limit reached waiting time is incorrect [bz1448854]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#484]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1448854

Platform: 
Win 10

Build
Beta 60.0b5

FxA & Sync server
STAGING 

STR:
1. Create a new account.
2. Upon email confirmation, make sure that the send SMS link page is opened.
3. Send the sms 5 times, until the sms limit is reached and a failure message is displayed.
4. Wait for the indicated amount of time (30 minutes).
5. Try to re-send the sms.
*6. Log out and login in with a different existing account.
 
Expected results:
After the waiting time displayed has expired, you should be able to re-send the sms.

Actual results:
- After the initial 30 minutes (as indicated in the message displayed), the waiting message appears again. This can indicate a 30 min or 1-hour waiting time until the next try. I got both.
*While waiting, logging out and trying to login with a different existing account will display the same message. Logging in is unsuccessful: https://www.screencast.com/t/OYgCHLWu

**Comment by vladikoff** [comment]
from mtg: clarify the behaviour of the customs server. should we fix this? need to figure it out

**Comment by shane-tomlinson** [comment]
Closing as fixed. Needs to be verified.
