### ISSUE TITLE
User account is locked meln_v@ukr.net [bz1452558]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#488]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1452558

Created attachment 8966127
Screenshot from 2018-04-09 11-36-11.png

Hello,
I can't log in to my Firefox Sync account cause it is locked(see screenshot in attachment).

Please investigate and unlock my account.

Thanks!

BR
Vitalii

**Comment by vladikoff** [comment]
This was fixed Thanks, it fixed the bug
