### ISSUE TITLE
Provision stage & production oauth credentials for "Screenshots" project [bz1455711]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#491]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1455711

Mirrored from https://github.com/mozilla-services/screenshots/issues/4308

I wouldn't mind confirmation of the other parameters for a relier here

Stage:
redirectUri: screenshots.stage.mozaws.net

Production:
redirectUri: screenshots.firefox.com

**Comment by jbuck** [comment]
Done
