### ISSUE TITLE
No unsubscribe button

### ISSUE THREAD

**Issue by Happy112** [mozilla/fxa-bugzilla-mirror#492]
Please,  re-open    https://github.com/mozilla/fxa-bugzilla-mirror/issues/409

See 

https://support.mozilla.org/en-US/forums/support-forum-contributors/712997#post-73870

**Comment by rfk** [comment]
We closed the "mirror" bug in #409 because it wasn't useful to deal with this in our github issue triage, but the underlying bug in bugzilla is still open: https://bugzilla.mozilla.org/show_bug.cgi?id=1410789

I'm going to comment over there to restart the conversation.
