### ISSUE TITLE
Cannot Reset Firefox Account Password "Your Email was just Returned. Mistyped Email?" message. [bz1459780]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#499]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1459780

User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
Build ID: 20180427210249

Steps to reproduce:

I tried to reset the password. It says  "Your Email was just Returned. Mistyped Email?"
My email is valid. Nothing received to reset in my inbox. The spam filter is off in my email client. 
I was out of country for a bit and my email account expired (I could not receive emails during that time). I've since renewed email account reusing same account and email address. 
Something happened during that time that's causing Firefox account reset emails to be stuck in limbo; it's like I need a hard reset or something. 

Actual results:

I was out of country for a bit and my email account expired (I could not receive emails during that time). I've since renewed email account reusing same account and same email address (the one tied to my Firefox account). 
Something happened during that time that's causing Firefox "password reset" emails to be stuck in limbo; it's like I need a hard reset or something. 

Expected results:

I should be able to get a password reset email in my inbox for the email account I have registered for my Firefox account. I forgot my password, so right now I cannot sign into my Firefox account, or reset the password. 
Please help me be able to log back into my Firefox Account.

**Comment by vladikoff** [comment]
Fixed!
