### ISSUE TITLE
When connecting with Sync, v60.0 connects briefly and disconnects.   Never syncs. [bz1460783]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#500]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1460783

User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Build ID: 20180503143129

Steps to reproduce:

I upgraded to v60.0 of Firefox on a Windows 7 PC.    Before (with v59?)   I couldn't sync two profiles on the same PC.   Now neither profile is able to Sync.   After starting the Sync process and logging in, I get the dialog box that Firefox has connected and a Sync will start momentarily, but it never starts.   By the time I go the menu to click on "Sync Now", the menu has already changed to "Re-connect to Sync", indicating that I have been disconnected.    The e-mail that I have connected does get sent to my e-mail account.

Actual results:

Now I can no longer sync my cellphone to my PC.   Not good.

Expected results:

I am told by Ciprian in your customer service that two profiles should on the same PC should be able to Sync (so I can share bookmarks), which never worked with v59.   Now with v6.0 neither profile on my PC can sync.   It connects and then disconnects shortly thereafter.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1460783#a16670988_481559
