### ISSUE TITLE
[SUMO User Issue]  Specific email not receiving emails Investigation of berceanu@runbox.com [bz1461705]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#501]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1461705

User: 
Support Case link

The user has tried the following:
*

I verified with the user that their email is indeed working. 

Can we investigate on our side what might be happening or to see if we can unlock the account by attached identity verification.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1461705#a5535917_481559
