### ISSUE TITLE
[SUMO User Issue]  Specific email not receiving emails Investigation of a@isml.me [bz1463007]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#502]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1463007

User: 
Support Case link
Sync Account Locked

The user has tried the following:
a@isml.me
I had a problem on my mail server so the email was not delivered, now it is working normally. I verified with the user that their email is indeed working. 

Can you unlock my account so i can authenticate other devices again.

**Comment by shane-tomlinson** [comment]
Closing as FIXED
