### ISSUE TITLE
Please change redirect_uri for oauth credentials of Mozilla IAM on FxA Stage [bz1465267]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#509]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1465267

Hi,

we would like to use FxA stage (https://oauth.stage.mozaws.net/) with our auth0 stage (auth-dev.mozilla.auth0.com)

I believe it's currently setup to allow redirect uris to auth0 prod (auth.mozilla.auth0.com).

Is it possible to change it so that the redirect uri is whitelisted to auth-dev.mozilla.auth0.com ?

client id: 1a118eae25503e99
env: stage (https://oauth.stage.mozaws.net/)
redirect_uri: https://auth-dev.mozilla.auth0.com/login

Just to be sure: please do *keep* the current redirect_uri on prod (https://oauth.accounts.firefox.com/)

thanks!

**Comment by shane-tomlinson** [comment]
This was fixed by @jbuck, closing.
