### ISSUE TITLE
My Firefox sync account was locked and i cant sign in. [bz1464955]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#511]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1464955

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Build ID: 20180516032328

Steps to reproduce:

I tried to reset password it didnt work

Actual results:

account is locked because email cant be verified but no email was sent to my email address 

Expected results:

i want to be able to sign in to my firefox sync account inder my primary email address of masterjpk69@yahoo.com

**Comment by vladikoff** [comment]
10 days no response, closed https://bugzilla.mozilla.org/show_bug.cgi?id=1464955
