### ISSUE TITLE
Firefox Account locked [bz1467070]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#513]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1467070

Created attachment 8983696
2018-06-06_11h30_01.png

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
Build ID: 20180307131617

Steps to reproduce:

I installed  firefox on my new laptop and want to restore my tabs password using firefox sync but when I try to log (password is correct) I got massage:

Sorry. We’ve locked your account.

The confirmation email we sent to fuks11@poczta.fm was returned and we’ve locked your account to protect your Firefox data.

If this is a valid email address, let us know and we can help unlock your account.
No longer own that email? Create a new account"
How to 

Actual results:

I can not recieve my account. also I can't change additional mail and also reset passoword

Expected results:

Please unlock my locked account

**Comment by shane-tomlinson** [comment]
Bugzilla bug marked as fixed, closing.
