### ISSUE TITLE
FxA login page zooms viewport when focusing on form fields [bz1467525]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#515]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1467525

Created attachment 8984223
Screen Shot 2018-06-07 at 2.02.49 PM.png

See screenshot.

**Comment by shane-tomlinson** [comment]
This should be fixed by https://github.com/mozilla/fxa-content-server/pull/6274 where we set the input element font-size to 16px. Fix will go into production the week of June 18th.
