### ISSUE TITLE
[SUMO User Issue]  Specific email not receiving emails Investigation of ben.griffiths@wems.co.uk [bz1468169]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#517]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1468169

User: 
Support Case link

The user has tried the following:
*

I verified with the user that their email is indeed working. 

Can we investigate on our side what might be happening or to see if we can unlock the account by attached identity verification. 

This is a follow up to the support request at https://support.mozilla.org/en-US/questions/1221352
As I understand it somehow my account has become locked so the Firefox Account authorisation codes sent via email do not work. I can reset my account password and temporaily log in, however that doesn't seem to fix the Firefox Account authorisation codes not working.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1468169#a4264411_481559
