### ISSUE TITLE
Firefox Sync error "Your email was just returned" [bz1468196]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#518]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1468196

Created attachment 8984832
ErrorMessage.PNG

User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Build ID: 20180516032328

Steps to reproduce:

I've doing a fresh install of Windows 8 on my desktop PC, after that, I downloaded and installed Firefox because it is my preffered web navigator but when I tried to login with my Firefox Sync account I get an error message saying "Your email was just returned".

I know that my issue was already reported (https://bugzilla.mozilla.org/show_bug.cgi?id=1382947) but, I asked for assistance in https://support.mozilla.org/ and they advised me to open a bug report with the purpose to unlock my email from the database of Firefox Sync.

My email is the same as used in this account in Bugzilla.

I hope that someone can help me with this incident, I consider Firefox as the better Free Web Navigator.

Additional Note: My email seems to be ok, I've received the email confirmation send by this website (BugZilla) and the email confirmation send by the Support website (Mozilla Support).

Thank you for your help.

Actual results:

I have tried to login with my Firefox Sync account but i get the error message "Your email was just returned". Also I have tried to reset my password throught the "Forgot my password" link, but the same error message appears.

Expected results:

I should've been able to login to my Firefox Sync account, or the "Forgot my password" link should work to unlock my Firefox Sync account.

**Comment by vladikoff** [comment]
Fixed!
