### ISSUE TITLE
[nb-NO] accounts.firefox.com shown in nn-NO even though nb-NO is available [bz1466480]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#521]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1466480

Using the Norwegian bokmål version of Firefox, accounts.firefox.com is shown in nn-NO even though nb-NO is available, and has been for a while.
I have verified that this applies to both the production site and the development site. I've also tested this with a clean profile.

**Comment by vladikoff** [comment]
Fixed
