### ISSUE TITLE
Two-step authentification menu is not translated for some languages [bz1468478]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#522]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1468478

Created attachment 8985151
Two Setp Authentification_Firefox Nightly.jpg

Device(s):
 -  Samsung S8+ (Android 8.0.0);

Build(s):
 - Nightly 62.0a1 (2018-06-12);
 - Beta 61.0b13
 - Release 60.0.2

Steps to reproduce:
 1. Go the browser language menu.
 2. Change browsers language to Arabic, Hebrew, Korean, Suomi, Hindi or Romania 
 3. Go to Two-step authentification menu

Expected result:
- Menu language is translated correctly

Actual result:
- Parts of the menu appear in EN instead of the language selected

Notes:
- For most the languages the menu is translated correctly.

**Comment by vladikoff** [comment]
Not translated yet!
