### ISSUE TITLE
Cannot change my email for the Firefox account service [bz1469785]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#523]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1469785

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Build ID: 20180605171542

Steps to reproduce:

I'm trying to change my email for addons.mozilla.org (which is linked to/works via Firefox account).

I cannot access my old email account which is why I cannot add a secondary email address because my primary address still requires a verification.

I'm stuck and I don't know what to do. I presume you still can change my email address directly via a SQL statement. Please do.

My former email is t dot artem at mailcity dot com

I've already successfully changed my bugzilla email - luckily it's a straightforward process. No so much for Firefox account.

**Comment by shane-tomlinson** [comment]
Closing as WONTFIX.
