### ISSUE TITLE
Can't disable Two Step Authentication [bz1470335]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#524]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1470335

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:60.0) Gecko/20100101 Firefox/60.0
Build ID: 20180605171542

Steps to reproduce:

1. Open menu and click on my user (Opens Firefox Sync setting page for my user)
2. Click disable on Two Step Authentication

Actual results:

Nothing happens and Javascript Console shows the error "Error: Unverified session".
I have tried reloading the page and using a private window.

Expected results:

Two Step Authentication is disabled

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1470335#a7140411_481559
