### ISSUE TITLE
How do I get Firefox sync to resend confirmation email [bz1470668]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#525]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1470668

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Build ID: 20180605171542

Steps to reproduce:

I had reinstalled operating system and FF. I tried to log into sync and FF sent a confirmation email to firefox@jctruscott.demon.co.uk, which is an alias.
Unfortunately I had recently changed email providers and I had to manually enter all aliases, but forgot the one for Firefox  :-(

Actual results:

I tried to log onto FF sync, but was told that the account was locked as the email had bounced, and I needed to contact FF for help.
The link is useless. I just end up going round in circles!!!

Expected results:

As I have now enabled the alias for my email address, I would have expected an option to resend the email.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1470668#a5619873_481559
