### ISSUE TITLE
Firefox sync error message "Your email was just returned" [bz1470711]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#526]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1470711

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Build ID: 20180605171542

Steps to reproduce:

After doing a fresh install of Windows 10, I downloaded and installed Firefox and attempted to login to Firefox Sync but get an error message saying "Your email was just returned". 

Actual results:

After multiple re-tries I still getting the "Your email was just returned" message. I've triple checked that I was entering all of my information correctly, but still get the error. Even rebooted the computer and tried again. Same error message. 
The option "forgut my password" did not work either "Your email was rejected".

Expected results:

I should've been able to log in to my Firefox Sync account.

**Comment by shane-tomlinson** [comment]
Closing as FIXED.
