### ISSUE TITLE
I can't access to my account since my Yahoo mail was hacked. [bz1472536]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#528]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1472536

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Build ID: 20180621125625

Steps to reproduce:

There was no way for me to login in to the Yahoo and to confirm sign in to my Firefox account. So I've created new with Gmail mail address but I need my bookmarks from old profile.

Actual results:

My account was locked within my Yahoo mail after multiple tries.

Expected results:

I expected nothing as there are two different mail addresses so merging was impossible.

**Comment by vladikoff** [comment]
this was closed in https://bugzilla.mozilla.org/show_bug.cgi?id=1472536#a78690_620229
