### ISSUE TITLE
Target some hotmail.fr addresses with the new email-service [bz1472619]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#532]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1472619

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Build ID: 20180605171542

Steps to reproduce:

Good morning and thanks for your help.
I recently changed the password of firefox sync on one of my machine, it was taken into account on the machine on which I made the change but impossible to make the validation request .....
I do not receive the verification email ...

Actual results:

I have no sync on my other device and it is relatively boring and therefore has no interest.

**Comment by jrgm** [comment]
Can someone tell me what exactly to add to the email config that works with the other socketlabs pattern in https://docs.google.com/document/d/1lc5T1ZvQZlhXY6j1l_VMeQT9rs1mN7yYIcHbRPR2IbQ/edit and what exactly the two email addresses are?

**Comment by vladikoff** [comment]
@philbooth @jrgm here's another email that's not `.fr` that we can add: https://bugzilla.mozilla.org/show_bug.cgi?id=1459499#c5

**Comment by philbooth** [comment]
Merde! I forgot about this, sorry.

I don't want to write the config in here because PII, will respond in the private channel...

**Comment by jrgm** [comment]
Okay. This is done. Noted in the deploy doc.

**Comment by vladikoff** [comment]
I'm excited for this!
