### ISSUE TITLE
Revoke OAuth credentials used by Hopscotch [bz1474719]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#536]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1474719

Hopscotch has been decommissioned, but (at least) 2 OAuth credentials were issued via bug 1404404 and bug 1404405

Please revoke those.

**Comment by vladikoff** [comment]
Fixed https://bugzilla.mozilla.org/show_bug.cgi?id=1474719#c1
