### ISSUE TITLE
I want to change my Firefox account password, but I get "wrong password" on the current one. [bz1476210]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#540]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1476210

Created attachment 8992556
Screenshot of the error (sorry it is in Italian, it means "wrong password")

User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Build ID: 20180704003137

Steps to reproduce:

Opened "manage account" to modify password

Actual results:

The current password field is prefilled, but after keying in the new password I get "wrong password" on the current one.

Expected results:

No error messages on the current password.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1476210#c5
