### ISSUE TITLE
problem with firefox sync impossible to revalid after mdp change [bz1472619]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-bugzilla-mirror#543]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1472619

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Build ID: 20180605171542

Steps to reproduce:

Good morning and thanks for your help.
I recently changed the password of firefox sync on one of my machine, it was taken into account on the machine on which I made the change but impossible to make the validation request .....
I do not receive the verification email ...

Actual results:

I have no sync on my other device and it is relatively boring and therefore has no interest.

**Comment by vladikoff** [comment]
Inactive
