### ISSUE TITLE
[SUMO User Issue]  Specific email not receiving emails Investigation of xxxx@xxx.xx [bz1481042]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-bugzilla-mirror#545]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1481042

User: 
Support Case link

The user has tried the following:
*

I confirmed that I deleted my own e-mail address.

Can we investigate on our side what might be happening or to see if we can unlock the account by attached identity verification.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1481042#a13686127_481559
