### ISSUE TITLE
Suggestion: Account/Sync: Manage or disconnect many devices simultaneous from sync [bz1481456]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-bugzilla-mirror#546]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1481456

Created attachment 8998177
Screenshot_2018-08-07 Firefox Accounts Devices apps.png

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
Build ID: 20180807100107

Steps to reproduce:

Need to remove or disconnect  many devices.
Please see the attached image.

https://screenshots.firefox.com/mHJIUsUDUF0mQsfF/accounts.firefox.com

- Sync many devices
- Replace devices
- Install new Operating Systems
- have many devices syncronized

Actual results:

Not east to remove many items.
I need to manage items more fast.

Expected results:

Checkbox for devices and massive disconnect.

Thanks!

**Comment by ryanfeeley** [comment]
@shane-tomlinson @davismtl  If we're not even recording these reasons, should we replace this dialog with a simple confirm?
