### ISSUE TITLE
Re-enable Leanplum prepush [bz1483974]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-bugzilla-mirror#547]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1483974

Over in https://bugzilla.mozilla.org/show_bug.cgi?id=1447298, we disabled Leanplum because the push notification options didn't appear in iOS settings when the user did not enable push notifications.

ISTM, that this might not be a bug because the user opted to not enable push notifications. By dismissing the Leanplum dialog, the native push dialog would not appear and therefore never prompted to enable and disable it. 

Is it correct that if the native push dialog doesn't appear, then the push options in iOS settings will not appear? Could we have another campaign trigger prompting them to enable push? If they accept, then notifications will appear in settings.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1483974#a12697679_481559
