### ISSUE TITLE
Accounts signup page throwing a 500 in the login frame. [bz1489306]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-bugzilla-mirror#548]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1489306

See here:

https://screenshots.firefox.com/qNYYHubIZwVfqEYT/null

Console output:

Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
LoginManagerContent: _detectInsecureFormLikes https://www.mozilla.org/en-US/firefox/accounts/ LoginHelper.jsm:71
Request to access cookie or storage on “https://accounts.firefox.com/?action=email&utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=accounts-page&utm_content=accounts-page&entrypoint=accounts-page&service=sync&context=fx_firstrun_v2&style=chromeless&haltAfterSignIn=true&origin=https%3A%2F%2Fwww.mozilla.org” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. accounts
Request to access cookie or storage on “https://accounts.firefox.com/?action=email&utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=accounts-page&utm_content=accounts-page&entrypoint=accounts-page&service=sync&context=fx_firstrun_v2&style=chromeless&haltAfterSignIn=true&origin=https%3A%2F%2Fwww.mozilla.org” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. common.945cfb8770ab.js:1:63698
<unavailable> appDependencies.bundle.js:55:79309
wrapMethod/t[e]
https://accounts-static.cdn.mozilla.net/bundle-8678c73705a1289422911be7ef29c5a29b852adc/appDependencies.bundle.js:55:79309
error
https://accounts-static.cdn.mozilla.net/bundle-8678c73705a1289422911be7ef29c5a29b852adc/app.bundle.en.js:1:34758
captureError
https://accounts-static.cdn.mozilla.net/bundle-8678c73705a1289422911be7ef29c5a29b852adc/app.bundle.en.js:9:15022
captureAndFlushError
https://accounts-static.cdn.mozilla.net/bundle-8678c73705a1289422911be7ef29c5a29b852adc/app.bundle.en.js:9:15165
fatalError
https://accounts-static.cdn.mozilla.net/bundle-8678c73705a1289422911be7ef29c5a29b852adc/app.bundle.en.js:9:15514
fatalError
https://accounts-static.cdn.mozilla.net/bundle-8678c73705a1289422911be7ef29c5a29b852adc/app.bundle.en.js:9:180792
startApp/<
https://accounts-static.cdn.mozilla.net/bundle-8678c73705a1289422911be7ef29c5a29b852adc/app.bundle.en.js:9:172357
(Async: promise callback) startApp
https://accounts-static.cdn.mozilla.net/bundle-8678c73705a1289422911be7ef29c5a29b852adc/app.bundle.en.js:9:172332
<anonymous>
https://accounts-static.cdn.mozilla.net/bundle-8678c73705a1289422911be7ef29c5a29b852adc/app.bundle.en.js:9:170194
LoginManagerContent: _detectInsecureFormLikes https://www.mozilla.org/en-US/firefox/accounts/
LoginHelper.jsm:71
Request to access cookie or storage on “https://accounts.firefox.com/?action=email&utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=accounts-page&utm_content=accounts-page&entrypoint=accounts-page&service=sync&context=fx_firstrun_v2&style=chromeless&haltAfterSignIn=true&origin=https%3A%2F%2Fwww.mozilla.org” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. app.bundle.en.js:1:45405
Request to access cookie or storage on “https://accounts.firefox.com/?action=email&utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=accounts-page&utm_content=accounts-page&entrypoint=accounts-page&service=sync&context=fx_firstrun_v2&style=chromeless&haltAfterSignIn=true&origin=https%3A%2F%2Fwww.mozilla.org” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. app.bundle.en.js:1:44144
Request to access cookie or storage on “https://accounts.firefox.com/?action=email&utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=accounts-page&utm_content=accounts-page&entrypoint=accounts-page&service=sync&context=fx_firstrun_v2&style=chromeless&haltAfterSignIn=true&origin=https%3A%2F%2Fwww.mozilla.org” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. app.bundle.en.js:9:239854

**Comment by vladikoff** [comment]
Closed
