### ISSUE TITLE
[SUMO User Issue]  Specific email address not receiving emails [bz1491681]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-bugzilla-mirror#549]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1491681

User: joshuaschultz@fastmail.com

May email is pay per month, after getting a new card, the email expired which caused my emails to that address to be returned.

I have now had my firefox account blocked.

I updated the card and tried to sign in, but it won't even try anymore, it just says blocked.

The user has tried the following:
* I can now access email, no email there to click (it was returned at the time of sending since my account was down)
* I waited 24 hours and tried again, still locked.

I have verified I can get into the account and have sent test emails. It is again receiving.

Can we investigate on our side what might be happening or to see if we can unlock the account by attached identity verification.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1491681
