### ISSUE TITLE
Confirmation email from Sync never arrives to address xxxxx@xxxx.net [bz1492991]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-bugzilla-mirror#550]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1492991

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0
Build ID: 20180830143136

Steps to reproduce:

Try to create (ok) then confirm (failed) Sync account 

Actual results:

no mail from Sync to confirm in my mailbox

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1492991#a9666933_481559
