### ISSUE TITLE
My Sync account is blocked. [bz1508266]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-bugzilla-mirror#556]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1508266

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0

Steps to reproduce:

Try to sync a new PC on firefox Sync

Actual results:

my address groconet@free.fr is blocked

Expected results:

I should have received an email from sync to add my new PC

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1508266#a4508052_481559
