### ISSUE TITLE
Difficult to login if not creating a new account [bz1513351]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-bugzilla-mirror#561]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1513351

Created attachment 9030546
Screenshot from 2018-12-11 14-43-56.png

The login screen (attached) is an account-creation screen.  If I want to login to an account I've already created, what do I do?

If I read the fine print at the bottom, there's a link I can click, but that's buried down in the footer where the terms-of-service and about-our-company links would go.

Expected: either a more obvious option to switch to a login view, or allow me to fill in the first two fields and hit enter to login (without double-entering password and age).

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1513351#a2928788_481559
