### ISSUE TITLE
Base32 decoding of FxA Recovery Key discards last character [bz1513360]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-bugzilla-mirror#562]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1513360

Noticed while testing [1].

STRs

1. Create a new account
2. Add a recovery key. If the least significant character (right-most) is not a digit, revoke the key and re-generate until it is a number. Save problematic recovery code somewhere.
  2a. (recovery key has problem) AH8T MRH4 NGKD 8X1T Y443 NGQX 4317
  2b. (recovery key does not have problem) AH8T MRH4 NGKD 8X1T Y443 NGQX 431A
3. Sign out, initiate a reset password.
4. Load the password reset link from the email.
5. Copy the the recovery code into the verification page. Change the least significant digit to another digit. (I always added one, perhaps that's important too). Submit the form.
6. Enter a new password.
7. Sign in.

Expected

In step 5, it should have told me the recovery key is invalid.

Actual

In step 5, I can continue on my way.

vbudhram noticed that if a digit other than the least significant character is changed, then the recovery key is rejected. If the least significant character is a letter, modifications are rejected.

[1] - https://github.com/mozilla/fxa-content-server/pull/6744

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1513360#c9
