### ISSUE TITLE
firefox (sync) account creation password rejection problem [bz1514469]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-bugzilla-mirror#564]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1514469

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

Steps to reproduce:

Accepted the offer from Firefox to setup Sync.
Chose to create a Firefox Account (to continue to Firefox Sync).
Entered a password of 17 characters, made up of several words.

Actual results:

Form verification highlighted my password box in red, and the flyout password guide had a red warning next to "Must not match this list of common passwords".

Expected results:

It should not have rejected the password on the basis of "match(ing) this list of common passwords".  Not only is my multi-word password not in that list of common passwords, not even the first word in my multi-word password is present in the list of 50k passwords.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1514469#a2613161_481559
