### ISSUE TITLE
Can't login with Initial email account if lose both 2-step verification device and recovery codes [bz1515880]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-bugzilla-mirror#565]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1515880

Created attachment 9032882
Operating procedures

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0 ID:20181220215605

When the user lost both 2-step verification device and recovery codes at the same time, he still needs to pass 2-step verification after resetting the password.

STR:
1.Due to lost both 2-step verification device and recovery codes, choose forgot password.
2.Enter the email address, click Create new password in the confirmation email to complete the reset in Firefox.
3.after the password is reset, the account will not be directly logged in on firefox, and need be verified.
4.In the option Resent Verification click is invalid, have to Remove Account and re-login.
5.Login with new password still requires 2-step verification.
(see attachment)

This may be a more extreme situation. But I think that even if the user loses the 2-step verification device, the email has already been verified by resetting the password. And resetting the password has cleared the server data. Then he can re-register the firefox account with the initial email.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1515880#a2102411_481559
