### ISSUE TITLE
[Shield] QA for Firefox Account discovery shield experiment extension 65 Release [bz1521602]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-bugzilla-mirror#570]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1521602

Hello all,

The code for phase 1 of the Firefox Account shield experiment extension has landed and is ready to be QA.

* Test plan - https://github.com/mozilla/fxa-discoverability-shield-study/blob/master/docs/TESTPLAN.md
* Extension - https://github.com/mozilla/fxa-discoverability-shield-study/blob/master/dist/firefox_account_browser_extension-1.0.0.zip

The PHD for this feature can be found here, https://docs.google.com/document/d/129HzVoufID4S2HRKMivXNW6BvlR6lYMa7Nyg-D-ZenA/edit

Please let me know if there is anything I am missing. Thanks!

**Comment by vladikoff** [comment]
To be closed in bugzilla
