### ISSUE TITLE
Add Firefox Monitor review app to stable.dev.lcip.org SNS queue for account delete messages [bz1525264]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#577]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1525264

Please configure the stable.dev.lcip.org SNS to publish account delete messages to https://blurts-server-review.herokuapp.com/ses/notification

I’ve set our review app the log those messages, and I want to see how it's delivered on the wire, so I can write the code to delete Monitor DB records for people who delete their FxA.

(Don’t mind the SES path typo; the only other SNS messages we receive are from SES … but I’ve got a follow-up to rename the path if this works.)

**Comment by shane-tomlinson** [comment]
@jbuck did this, closing as done!
