### ISSUE TITLE
Please provision oauth credentials for Fenix [bz1528355]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#584]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1528355

We are now integrating FxA into Fenix and need a unique client_id as well. So, we basically need the same (see below) done for Fenix.

+++ This bug was initially created as a clone of Bug #1503456 +++

We have a bunch of OKRs around adding various app-services functionality into the android-components Reference Browser.  Let's get it set up so that reference-browser can use the production FxA stack rather than a dev environment.

First order of business is to allocate a unique OAuth client_id and get it configured appropriately.  I'll start with making one in the dev environment.

**Comment by shane-tomlinson** [comment]
Resolved as FIXED. Closing.
