### ISSUE TITLE
FxA + Sync Discoverability w/Avatar - Browser Feature for Release 66/67 [bz1524665]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#588]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1524665

https://docs.google.com/document/d/129HzVoufID4S2HRKMivXNW6BvlR6lYMa7Nyg-D-ZenA/edit

**Comment by shane-tomlinson** [comment]
DONE!
