### ISSUE TITLE
turn on config enablePruning in production [bz1130193]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#59]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1130193

This never got enabled and fell off the radar. My fault. We need to turn on enablePruning in production (and re-estimate if we can just turn it on, or if we need to do little trimming if the tables are too large (shouldn't be)).

**Comment by vladikoff** [comment]
@rfk do we still need this?

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1130193#c8
