### ISSUE TITLE
Add custom telemetry hooks for FxA browser menu [bz1535937]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#610]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1535937

This issue is to track adding custom telemetry hooks for the FxA browser menu. Please reference https://docs.google.com/spreadsheets/d/1IYiGluQzNIe3Lj6x9gIwGhDTBPEEfp-R4T4UsVIb9Cg/edit#gid=0 for details on which metrics should be tracked.

**Comment by vbudhram** [comment]
This is still in review, but won't make 134.

**Comment by vbudhram** [comment]
This has landed and marked as `RESOLVED FIX` in bugzilla, not sure why it didn't get closed here.
