### ISSUE TITLE
[FFOS 2.2] The password is not revealed when tapping the "show password" check box in the reset pin flow [bz1132481]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#62]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1132481

Steps to reproduce:
1. Open the stage app and find a paid app.
2. Press the price button to start the purchase flow.
3. Press the "Forgot your pin" link and then the "Reset" button.
4. Click the "Sign in" button.
5. Enter your password and tap the "Show password" check box

Expected results:
The password is revealed.

Actual results:
The password is not revealed.

Notes/Issues:
Verified in FFOS 2.2 (Flame) using the stage app.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1132481#c3
