### ISSUE TITLE
Add FxA menu under the app (hamburger) menu [bz1542334]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#623]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1542334

As a follow up to https://bugzilla.mozilla.org/show_bug.cgi?id=1524665, we wanted to expose the same menu under the hamburger menu.

Please reference the designs at https://mozilla.invisionapp.com/share/HWQTPQL7Y2Q#/screens/350225002_Option_1 for more details.

**Comment by vbudhram** [comment]
Bumping this to train 136 because it needs to be updated with telemetry.

**Comment by vbudhram** [comment]
This has landed and will be in FF 68, closing.
