### ISSUE TITLE
Firefox accounts - User can create and access new account for an email account not owned by the user. [bz1543160]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#624]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1543160

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

Steps to reproduce:

1. User A goes to to accounts.firefox.com
2. Create an account with an emailID for User B - something@b.com (not owned by User A and does not have a Firefox account.)
3. something@b.com receives the verification email. 
   a. When the email is sent from account.firefox.com, it does not contain IP address, location of the machine which attempted to create an account.
   b. User B now clicks on the link.

Actual results:

1. At this point the browser used by A to create account is also logged in + plus has access to the account of B.
2. Can change display pictures, notifications options, set recovery key, secondary email etc.

Expected results:

Expected behaviour is to only log in to the browser instance of User B - the instance in which verification email is opened and not in the instance from where it's sent.

Also, the User A can visit garbage pages, unfit content etc and keep syncing to create troubles for User B. 

Whenever User B decides to use something@b.com with Firefox accounts for after going through the process of reset password,  the same garbage, unfit content will now be on the B's machine.

Did not check if it's possible:
1. To reset password with only access to secondary email - which is User A's controlled email.
2. Recovery data without having access to primary email but by just using the recovery key which User A generated during the account creation phase.

**Comment by shane-tomlinson** [comment]
As mentioned in the bug, under all but the most contrived circumstances this is not possible. The example is to register an another person's address and hope they click the verification link. Even then, the only power the account has is to sync with itself, for the attack to do anything meaningful, the target would need to sign into the account with the same password as the attacker.
