### ISSUE TITLE
Better support for self-hosted sync [bz1502715]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#626]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1502715

User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0

Steps to reproduce:

The current system of Firefox Sync is deeply tied into the Mozilla accounts framework, making it extremely difficult to fully self-host the sync data.

Some people would rather have full control of their private sync data, rather than trusting it (or its encryption key) to a third-party such as Mozilla.

However, setting this system up is both prohibitively over-complicated, and comes with a huge set of warnings about potential security issues.

Actual results:

There is no easy way to set up fully-self hosted sync.
Firefox Account is extremely complex and convoluted, requiring a huge number of interconnected services (or interconnected Docker containers), while not even being necessary for the actual feature of synchronising profile data.

Expected results:

There should be a simple way to set up fully self-hosted Sync, with no dependence on Mozilla servers, preferably as simply as installing a supported Docker container and setting up the appropriate forwarding address.

**Comment by clouserw** [comment]
You're correct - this is a complex system and it requires some time and expertise to set up.  Specific quality-of-life changes are welcome as patches, but as a high level bug this isn't something we're going to track.  Closing this.
