### ISSUE TITLE
retrieve account [bz1545064]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#627]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1545064

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

Steps to reproduce:

Hello, I have not signed for three years over my Mozilla account today want to get it back, but did not succeed, because both were unsuccessful reset the password or retrieve username by mail. I applied for a re-activated on https://support.mozilla.org/zh-CN/users/auth, but did not receive the activation email. cc yxu@mozilla.com

**Comment by shane-tomlinson** [comment]
I moved this over to SUMO product, closing here.
