### ISSUE TITLE
Adding Firefox Accounts Thai [th] locale [bz1545994]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#628]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1545994

User Agent: Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/73.0.3683.68 Mobile/15E148 Safari/605.1

Steps to reproduce:

The Thai [th] localization of Firefox Accounts is now complete, but when I go to Firefox Accounts login page, it seems that Firefox Accounts still doesn’t support Thai.

Expected results:

Please add support for Thai [th]. I would like to have Thai locale being a part of it.

**Comment by clouserw** [comment]
This is done!  Thanks
