### ISSUE TITLE
Change registered name of Fenix to Firefox Sync on the OAuth server [bz1547251]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#633]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1547251

In Bug #1528355 OAuth credentials for Fenix were created using the name Fenix.

Per https://github.com/mozilla/fxa/issues/913, the name should be changed to "Firefox Sync"

The client_id is a2270f727f45f648

:jbuck, this change needs to be reflected in both Stage and Prod

**Comment by vbudhram** [comment]
This is resolved in bugzilla, but still open. Thoughts @vladikoff?

**Comment by vladikoff** [comment]
Resolved 👍
