### ISSUE TITLE
Firefox Send login in didn't work in Tor Browser [bz1542291]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#643]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1542291

User Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
Firefox for Android

Steps to reproduce:

Use tor to login in Firefox Send normally

Actual results:

It said "something went wrong" and couldn't login in successfully.

Expected results:

Login in normaily

**Comment by shane-tomlinson** [comment]
Dup of https://github.com/mozilla/fxa-content-server/issues/4609, closing.
