### ISSUE TITLE
The input values from about:welcome page  are not set [bz1554102]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#652]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1554102

Created attachment 9067262
Actual result.png

Affected versions:

Tested on Nightly 69.0a1 (2019-05-23)

Affected platforms:

Tested on Mac OS 10.14 and Windows 10

Prerequisites:
To be able to see the about:welcome page on a version where this is not implemented please go to about:config and set:

identity.fxaccounts.autoconfig.uri to https://latest.dev.lcip.org/
browser.newtabpage.activity-stream.fxaccounts.endpoint to https://latest.dev.lcip.org/
Restart the browser.

Steps:  

1. Go to about:welcome page
2. Click Menu button
3. Select Web developer option
4. Select Inspector option
5. Inspect "Enter email" field
6. Check the following inputs:
- input name = "device_id"
- input name = "flow_id"
- input name = "flow_begin_time" 

Expected result:

The three inputs show a numeric value (always random number), this values should never show "0" or blank.

Actual result:

For input name = "device_id" and input name = "flow_id" value is blank
For input name = "flow_begin_time" value = 0

Regression range:

With the Nightly build 69.0a1(2019-05-22) the issue is not reproducible, but with Nightly build 69.0a1(2019-05-23) the issue is reproducible.

Note:

Maybe this bug can be related to this one:

https://bugzilla.mozilla.org/show_bug.cgi?id=1553205

**Comment by shane-tomlinson** [comment]
Dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1553205
