### ISSUE TITLE
About:welcome page links are not properly highlighted when pressing TAB key [bz1554282]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#655]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1554282

Created attachment 9067412
Trailhead - Welcome page - Tab contrast.JPG

**Prerequisites:**
- To be able to see the about:welcome page on a version where this is not implemented please go to about:config and set:

1. identity.fxaccounts.autoconfig.uri to https://latest.dev.lcip.org/
2. browser.newtabpage.activity-stream.fxaccounts.endpoint to https://latest.dev.lcip.org/
3. Restart the browser.

**Affected versions**
Tested on Nightly 69.0a1 (2019-05-23)

**Affected platforms**
Tested on Windows 10

**Steps to reproduce**
1. Go to about:welcome page
2. Press the "TAB" key to navigate the available links

Actual result: the link is highlighted in a faded color.

Expected result: the link to be highlighted in a lighter color, for example as in the attached page (also part of the same flow).

**Comment by shane-tomlinson** [comment]
Moved this to the about:newtab component in bugzilla, not a problem with FxA. Closing.
