### ISSUE TITLE
Trailhead - Create a Firefox Account page - page design is outdated [bz1554305]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#657]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1554305

Created attachment 9067440
create your account - Firefox old logo.JPG

**Prerequisites:**

To be able to see the about:welcome page on a version where this is not implemented please go to about:config and set:

1. identity.fxaccounts.autoconfig.uri to https://latest.dev.lcip.org/
2. browser.newtabpage.activity-stream.fxaccounts.endpoint to https://latest.dev.lcip.org/
3. Restart the browser.

**Affected versions:**
Tested on Nightly 69.0a1 (2019-05-24)

**Affected platforms:**
Tested on Windows 10

**Steps to reproduce:**

1. Go to about:welcome page
2. Enter a valid email address
3. Click "Continue" to reach the "Create a Firefox Account" page.

**Expected result:**
The Firefox logo is the old design. 
Note that the page's design is different from the expected result.

**Comment by shane-tomlinson** [comment]
Dup of https://github.com/mozilla/fxa/issues/1241, closing.
