### ISSUE TITLE
Features icons and text are arranged incorrectly at the bottom of the Form. [bz1554682]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#659]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1554682

Created attachment 9067771
create form.PNG

**Note**
* Prerequisites:
To be able to see the about:welcome page on a version where this is not implemented please go to about:config and set:
* identity.fxaccounts.autoconfig.uri to https://latest.dev.lcip.org/
* browser.newtabpage.activity-stream.fxaccounts.endpoint to https://latest.dev.lcip.org/
* Restart the browser.

**Affected versions**
* Tested on Nightly 69.0a1 (2019-05-27)

**Affected platforms**
* Tested on Windows 10

**Steps to reproduce**
1. Go to about:welcome page
2. Enter valid email account.
3. Click "Continue".

**Expected result**
* Features icons and text are displayed on the right side of the Form.

**Actual result**
* Features icons and text are arranged incorrectly at the bottom of the Form.

**Comment by shane-tomlinson** [comment]
Closed as dup of https://github.com/mozilla/fxa/issues/1241
