### ISSUE TITLE
Trailhead - Email template CTA button doesn't have round edges [bz1554687]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#661]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1554687

Created attachment 9067778
activate account email actual result.JPG

**Prerequisites:**

To be able to see the about:welcome page on a version where this is not implemented please go to about:config and set:

1. identity.fxaccounts.autoconfig.uri to https://latest.dev.lcip.org/
2. browser.newtabpage.activity-stream.fxaccounts.endpoint to https://latest.dev.lcip.org/
3. Restart the browser.

Make sure you have an email account to test. You can check email template here:
1. Go to http://www.yopmail.com/en/
2. In "Type the Email name of your choice:" , type "moztest"
3. Click on "Check Inbox"
4. Example template can be found under subject "Finish Creating Your Account"

**Affected versions:**
Tested on Nightly 69.0a1 (2019-05-27)

**Affected platforms:**
Tested on Windows 10

**Steps to reproduce:**

1. Go to about:welcome page
2. Enter a valid email address
3. Click "Continue" to reach the "Create a Firefox Account" page.
4. Fill in the password and age, and click "Create Account"
5. Click "Continue" 
6. "One last step" page displays. Go to http://www.yopmail.com/en/
7. In "Type the Email name of your choice:" , type "moztest"
8. Click on "Check Inbox"
9. Example template can be found under subject "Finish Creating Your Account"
10. Make sure you click on "--Show pictures. -- Under the date of the email, so you can see the complete email template.

**Actual result:**
"Confirm email" CTA button is rectangular, with sharp edges. See screenshot attached to this comment.

**Expected result:**
As per document https://docs.google.com/document/d/1O0ZkCblQ1sVEuU2uQ1Do8vBqAVTuP7ZX82XQxFkJkoo/edit# , page 10, "Confirm email" CTA should be rectangular, with round soft edges. See screenshot attached in the next comment for further reference.

**Comment by shane-tomlinson** [comment]
Closed as WONTFIX, the rounded corners show in gmail, yahoo, hotmail, and zoho.

### gmail

![gmail-verification.png](https://images.zenhubusercontent.com/5c9e44f8850e6a34fc6eeffc/9d489f09-cae8-4335-9657-72b002539cf3)

### hotmail
![hotmail-verification.png](https://images.zenhubusercontent.com/5c9e44f8850e6a34fc6eeffc/2980f0cd-7c40-4daa-b945-9c93074441ed)

### yahoo
![yahoo-verification.png](https://images.zenhubusercontent.com/5c9e44f8850e6a34fc6eeffc/bdfe4beb-7022-4a57-a7f2-c72641063ff0)

### zoho

![zoho-verification.png](https://images.zenhubusercontent.com/5c9e44f8850e6a34fc6eeffc/1f0adc1a-b2f2-4f60-8d12-585c15739378)
