### ISSUE TITLE
Trailhead - Fx Confirmed Account Email template CTA button doesn't have round edges [bz1554732]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#664]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1554732

Created attachment 9067838
fx account confirmed email actual result.JPG

**Prerequisites:**

To be able to see the about:welcome page on a version where this is not implemented please go to about:config and set:

1. identity.fxaccounts.autoconfig.uri to https://latest.dev.lcip.org/
2. browser.newtabpage.activity-stream.fxaccounts.endpoint to https://latest.dev.lcip.org/
3. Restart the browser.

Make sure you have an email account to test. You can check email template here:
1. Go to http://www.yopmail.com/en/
2. In "Type the Email name of your choice:" , type "moztest"
3. Click on "Check Inbox"
4. Example template can be found under subject "Finish Creating Your Account"

**Affected versions:**
Tested on Nightly 69.0a1 (2019-05-27)

**Affected platforms:**
Tested on Windows 10

**Steps to reproduce:**

1. Go to about:welcome page
2. Enter a valid email address
3. Click "Continue" to reach the "Create a Firefox Account" page.
4. Fill in the password and age, and click "Create Account"
5. Click "Continue" 
6. "One last step" page displays. Go to http://www.yopmail.com/en/
7. In "Type the Email name of your choice:" , type "moztest"
8. Click on "Check Inbox"
9. Example template can be found under subject "Finish Creating Your Account"
10. Make sure you click on "--Show pictures. -- Under the date of the email, so you can see the complete email template.
11. Click on "Confirm email"
12. Go back to inbox
13. Select email with subject: "Your Firefox Account is Confirmed"

**Actual result:**
"Connect another device" CTA button is rectangular, with sharp edges. See screenshot attached to this comment.

**Expected result:**
As per the CTA design of document https://docs.google.com/document/d/1O0ZkCblQ1sVEuU2uQ1Do8vBqAVTuP7ZX82XQxFkJkoo/edit#  "Connect another device" CTA should be rectangular, with round soft edges. See screenshot attached in the next comment for further reference.

**Comment by shane-tomlinson** [comment]
Closed as WONTFIX, the corners display as expected in gmail, hotmail, yahoo and zoho

### google
<img width="751" alt="verified-google" src="https://user-images.githubusercontent.com/848085/58553239-55ab0300-820c-11e9-8dc9-e0c6ddfa248b.png">

### yahoo

<img width="842" alt="verified-yahoo" src="https://user-images.githubusercontent.com/848085/58553240-55ab0300-820c-11e9-8ecc-f25b203b22c6.png">

### hotmail
<img width="726" alt="verified-hotmail" src="https://user-images.githubusercontent.com/848085/58553241-55ab0300-820c-11e9-90c2-577f953fb9e8.png">

### zoho
<img width="703" alt="verified-zoho" src="https://user-images.githubusercontent.com/848085/58553242-55ab0300-820c-11e9-83ff-720fa24af39f.png">
