### ISSUE TITLE
"Firefox Cloud Terms of Service" link is missing on confirmation email [bz1555063]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#671]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1555063

Created attachment 9068087
email confirmation link missing.PNG

**Note**
* Prerequisites:
To be able to see the about:welcome page on a version where this is not implemented please go to about:config and set:
identity.fxaccounts.autoconfig.uri to https://latest.dev.lcip.org/
browser.newtabpage.activity-stream.fxaccounts.endpoint to https://latest.dev.lcip.org/
Restart the browser.

**Affected versions**
* Tested on Nightly 69.0a1 (2019-05-28)

**Affected platforms**
* Tested on Windows 10

**Steps to reproduce**
1. Go to about:welcome page
2. Enter valid email account.
3. Click "Continue".
4. Complete the fields.
5. Click "Create account"
6. Click on "Continue"
7. Open the email.
8. check the verification email links at the bottom.

**Expected result**
* "Firefox Cloud Terms of Service" link is displayed on confirmation email

**Actual result**
* "Firefox Cloud Terms of Service" link is missing on confirmation email

**Comment by clouserw** [comment]
@ryanfeeley these look like two different designs.  Which is correct?

**Comment by clouserw** [comment]
This will be addressed with https://github.com/mozilla/fxa/issues/1327
