### ISSUE TITLE
Avatar profile picture in "Sign in to your Firefox account" page isn't matching the specs [bz1555345]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#678]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1555345

Created attachment 9068384
Sign in to your Firefox account.png

[Affected versions]: 
Firefox 67.0.1

[Affected platforms]:
Platforms: Windows 10 x 64, Windows 7 x 64, Mac OS 10.14 and Ubuntu 18.04

[Prerequisites]:
To be able to see the about:welcome page on a version where this is not implemented please go to about:config and set:
identity.fxaccounts.autoconfig.uri to https://accounts.stage.mozaws.net
browser.newtabpage.activity-stream.fxaccounts.endpoint to https://accounts.stage.mozaws.net

[Steps to reproduce]:
1. Go to about:welcome page.
2. Enter a known account in email field and then click on Continue button.
3. Observe the avatar profile picture.

[ Expected result]:
Avatar profile picture in "Sign in to your Firefox account" page should be matching the specs.

[Actual result]:
Avatar profile picture in "Sign in to your Firefox account" page isn't matching the specs.

**Comment by shane-tomlinson** [comment]
Fixed by @jbuck last night, closing as FIXED.
