### ISSUE TITLE
FxA and sync servers get a "B" on SSLlabs tests [bz1219547]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#80]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1219547

The core servers for the FxA connected experience all get a "B" rating from SSLLabs, e.g:

  https://www.ssllabs.com/ssltest/analyze.html?d=accounts.firefox.com
  https://www.ssllabs.com/ssltest/analyze.html?d=token.services.mozilla.com

The reason it gives is that:

  "This server supports weak Diffie-Hellman (DH) key exchange parameters.
   Grade capped to B."

Sadly I don't think we can do anything about that yet, but I wanted a bug on file to track it (and to point at when this topic comes up again).

The reasoning behind the current situation is that we have certain clients (e.g. old android devices, partner devices like Bug 1186900) that do not support the "modern" TLS configuration recommended in [1].  Instead we must use the "intermediate" configuration [2] which includes DH ciphers.

These ciphers are fine _if_ you use secure DH parameters.  But the TLS support for FxA and Sync is provided by Amazon's Elastic Load Balancers, which don't let you customize the DH parameters.

So I think we're stuck on a "B" grade until all our clients grow more modern TLS support, or Amazon gives us better tools to customize TLS on the ELBs.

[1] https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility
[2] https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29

**Comment by vladikoff** [comment]
from mtg: it seems there are some posts on AWS boards that there are ways to bring SSLLabs score back to A but @jrgm notes that we might exclude some browsers if we enable it.

cc @rfk

**Comment by vladikoff** [comment]
i.e Android 2.3, can we just drop that cypher?

**Comment by rfk** [comment]
> Android 2.3, can we just drop that cipher?

We'd need to get metrics on use of that cipher in practice; removing it might break e.g. SBrowser

**Comment by shane-tomlinson** [comment]
@jbuck is finding the SBrowser stats now.

**Comment by jbuck** [comment]
https://github.com/mozilla-services/svcops/issues/1335 from February had some stats. I'll run another query now

**Comment by jbuck** [comment]
Stats at https://docs.google.com/spreadsheets/d/1iLn1mh4QcQyQm96U6UIXx3Ty8gVhIgf2sKZcnTw6khI/edit#gid=0

**Comment by vbudhram** [comment]
from mtg: closing this for now
