### ISSUE TITLE
Notify any open Firefox Accounts tabs of about:preferences#sync device name change [bz1221111]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#86]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1221111

As part of the "devices view" of Firefox Accounts, any open FxA tabs should be notified if the user changes the device name from about:preferences#sync

See https://github.com/mozilla/fxa/blob/rfk/devices-view-requirements/features/FxA-16-devices-view/README.md

**Comment by vladikoff** [comment]
Related to https://github.com/mozilla/fxa-content-server/issues/3252
