### ISSUE TITLE
Pressing "Show" on reset password page reveals both password fields [bz1229748]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#99]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1229748

Reproduced on Mac OS X 10.11 using:
*Firefox 42
*Firefox 43 beta 8
*latest 44.0a2 Aurora
*latest 45.0a1 Nightly

STR:
*pre-requisite:
**the user has a FxAccount.
1. Open Firefox using a clean profile.
2. Click on one of the available Sync buttons (e.g. about:home, about:preferences#sync, menu panel, Tools).
3. Select “Sign in” and click the "Forget password?" link.
4. Enter your email address and wait for the 'Reset password........' email. Click on the link received in the email
5. Enter some data in the new/repeat password textures.
6. Select “Show” for the New Password field.

Expected Result:
The text within the New password field is revealed. 

Actual Result:
The text from the both fields is revealed.

Screenshot:
http://i.imgur.com/rEce2rH.png

Notes:
This issue also reproduces on Windows 7 64-bit, Windows 7 32-bit and Ubuntu 14.04 32-bit.
This is not a recent regression.

**Comment by shane-tomlinson** [comment]
@rfk - this behavior was by design. @ryanfeeley - care to weigh in?

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/311.

**Comment by shane-tomlinson** [comment]
I closed the referenced bugzilla bug as a dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1010201
